### ISSUE TITLE
Can't darken zeronet

### ISSUE THREAD

**Issue by gogonkt** [m-khvoinitsky/dark-background-light-text-extension#104]
Hi Dear:
Thank you for developed this!

I want to report a bug:
It can't darken zeronet (http://127.0.0.1:43110/) all webpage after It auto upgraded after this afternoon. I can't get any idear.

firefox 56.0, 64bit, win 7

All the best
Erik

**Comment by m-khvoinitsky** [comment]
I don't have zeronet installed. Please, test against latest 0.6.3 version and report back whether the problem is still exists.
Thank you.
