### ISSUE TITLE
CTAN: unreadable black text

### ISSUE THREAD

**Issue by tobiasBora** [m-khvoinitsky/dark-background-light-text-extension#105]
Hello,

First thank you for your work, I've been using this extension for some time, and I really like it. Since the last update however, some stuff has been broken. For example, on CTAN, the text of the description is black, while the title text has the good (light) color: [https://ctan.org/pkg/geometry](https://ctan.org/pkg/geometry)

Another strange behaviour is on https://tex.stackexchange.com/, where all the background is grey, while this color is not defined at all in the configuration of the plugin.

Thank you again,

tobiasBora.

PS: Here are two screenshots to illustrate the problem:
![spectacle z29741](https://user-images.githubusercontent.com/2164118/32672357-02480326-c64b-11e7-9f13-08a435c37de8.png)
![spectacle t29741](https://user-images.githubusercontent.com/2164118/32672377-154d64b6-c64b-11e7-8b76-3c04da92bc51.png)

**Comment by m-khvoinitsky** [comment]
Seems to be fixed in one of recent bugfix releases. Can you confirm that everything works in 0.6.3?

**Comment by m-khvoinitsky** [comment]
I suppose you use ESR, doesn't you?

**Comment by tobiasBora** [comment]
Hello,

Sorry to answer that late, I missed your answer. Indeed the bugfix fixed the problem, and I'm indeed running ESR.

Thank you!
