### ISSUE TITLE
Broken Gmail page

### ISSUE THREAD

**Issue by cges30901** [m-khvoinitsky/dark-background-light-text-extension#107]
It seems that this extension breaks Gmail page. If I disable this in about:addons, Gmail works again. I am using Firefox 56.0.2 and Dark Background and Light Text 0.6.1
![screenshot_2017-11-11_21-30-42](https://user-images.githubusercontent.com/19516286/32689904-d2b0e03c-c727-11e7-9822-f659634804a7.png)

**Comment by cges30901** [comment]
Gmail works after I downgrade Dark Background and Light Text to version 0.6.0

**Comment by cookieboyeli** [comment]
I can confirm this

**Comment by m-khvoinitsky** [comment]
Try 0.6.2, I've just fixed a regression introduced in 0.6.1.

**Comment by cookieboyeli** [comment]
I don't know how to compile it. I can only install add ons from file as .jar or .xpi.

I know it's not the place to ask but can you point me in the right direction so I can compile it myself or get a precompiled build?

**Comment by m-khvoinitsky** [comment]
It's already on addons.mozilla.org

**Comment by cges30901** [comment]
Thanks! It is working now.

**Comment by cookieboyeli** [comment]
Wow that was fast. Yup, it's working.
