### ISSUE TITLE
anything at flickr.com doesn't load

### ISSUE THREAD

**Issue by t-o-d-d** [m-khvoinitsky/dark-background-light-text-extension#110]
No page at flickr.com would load at all with the previous update. Pages would stick in loading loops. The 11-11 update made it so flickr pages will load with the addon enabled, but they hang FF for quite a while before they load. 

Great plugin by the way. A real eye saver.  ;)

**Comment by m-khvoinitsky** [comment]
Seems to be fixed in 0.6.6, see #114

**Comment by t-o-d-d** [comment]
indeed it is.. thanks!
