### ISSUE TITLE
Stylesheet processor don't work at youtube.com on FF esr & lost checkbox "enabled"

### ISSUE THREAD

**Issue by RiNoWaR** [m-khvoinitsky/dark-background-light-text-extension#111]
after update at version 0.6 and above (last check 0.6.3) method "stylesheet processor" don't work at youtube.com on FF esr and other some sites(http://steamgifts.com/)
plus: a new tab page opening always will blink a wite background with the used method "stylesheet processor", don't fix sence version 0.5.11 (checked at youtube.com)

после обновления до версии 0.6 и выше(последняя проверка на версии 0.6.3) используемый метод "stylesheet processor" перестал корректно отрабатывать на ветке FF esr, проявляется на сайте youtube.com и некоторых других, например steamgifts.com.
так же: при открытии новой страницы(new tab) любой фон разово моргает белым, это при том, что при загрузке виден корректно наложенное оформление из дополнения. Т.е. в процессе прогрузки страницы с корректно наложенным оформлением из  "stylesheet processor" страница разово моргает белым фоном, это не было исправлено с версии 0.5.11

**Comment by RiNoWaR** [comment]
btw, lost a checkbox "enabled" in addon's icon, placed into action panel

между прочим пропал чекбокс "enabled" с иконки дополнения выведенной на панель доступа

**Comment by RiNoWaR** [comment]
btw, lost a checkbox "enabled" in addon's icon, placed into action panel

**Comment by m-khvoinitsky** [comment]
> после обновления до версии 0.6 и выше(последняя проверка на версии 0.6.3) используемый метод "stylesheet processor" перестал корректно отрабатывать на ветке FF esr, проявляется на сайте youtube.com и некоторых других, например steamgifts.com.

Проверил на 52.4.1 — работает. Есть ли ошибки в Browser Console?

> lost checkbox "enabled"

Можно скриншот? см. https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Debugging#Debugging_popups про то, как выключить автозакрытие поп-апов при потере фокуса, если это мешает сделать скриншот.

> после обновления до версии 0.6 и выше(последняя проверка на версии 0.6.3) используемый метод "stylesheet processor" перестал корректно отрабатывать на ветке FF esr, проявляется на сайте youtube.com и некоторых других, например steamgifts.com.
так же: при открытии новой страницы(new tab) любой фон разово моргает белым, это при том, что при загрузке виден корректно наложенное оформление из дополнения. Т.е. в процессе прогрузки страницы с корректно наложенным оформлением из "stylesheet processor" страница разово моргает белым фоном, это не было исправлено с версии 0.5.11

см. https://github.com/m-khvoinitsky/dark-background-light-text-extension/issues/71#issuecomment-340042356

**Comment by RiNoWaR** [comment]
> после обновления до версии 0.6 и выше(последняя проверка на версии 0.6.3) используемый метод "stylesheet processor" перестал корректно отрабатывать на ветке FF esr, проявляется на сайте youtube.com и некоторых других, например steamgifts.com.
> Проверил на 52.4.1 — работает. Есть ли ошибки в Browser Console?

проверил на 52.5.0 версию 0,6,4 сейчас проблем не наблюдается c методом "stylesheet processor": цветовое оформление накладывается на youtube & steamgifts. На версии ff52.4 было ранее. Исправлено.

> lost checkbox "enabled"
тут есть чекбокс, при чем везде показывается
![v0 5 11 chekbox](https://user-images.githubusercontent.com/33617286/32823760-c1473152-c9f7-11e7-85e5-f7e52280696c.jpg)
тут уже нет его
![v0 6 4 chekbox](https://user-images.githubusercontent.com/33617286/32823787-dd478cda-c9f7-11e7-92a9-8a96a6cb080f.jpg)

по поводу "моргания" белым фоном, судя по комментарию это "фича" ff. 
Ок.

**Comment by RiNoWaR** [comment]
классное дополнение, надеюсь оно и дальше будет таким же удобным

**Comment by m-khvoinitsky** [comment]
> проверил на 52.5.0 версию 0,6,4 сейчас проблем не наблюдается c методом "stylesheet processor": цветовое оформление накладывается на youtube & steamgifts. На версии ff52.4 было ранее. Исправлено.

Кое-что касательно ESR было исправлено в 0.6.3. Скорее всего это оно.

> тут уже нет его v0.6.4

Это Windows 10? Какая тема Windows и Firefox используется?

**Comment by RiNoWaR** [comment]
> Кое-что касательно ESR было исправлено в 0.6.3. Скорее всего это оно.

могу поставить версию 06,3 и еще раз проверить, но на прошлой версии ff eык были те проблемы, сейчас уже стоит последняя ff esr и с этим нет проблем.

> Это Windows 10? Какая тема Windows и Firefox используется?

windows 10 да,  в персонализации написано "текущая тема: windows"
у ff стоит тема "FT DeepDark"

По поводу морганию белым фоном, могу скинуть лог консоли и скрин в момент моргания на странице youtube

**Comment by m-khvoinitsky** [comment]
Про отсутствие checkbox: проблема вызвана "FT DeepDark". Не уверен, что это легко будет починить, тем более в Firefox 57+ complete-темы больше не работают, т. е. большого смысла в этом нет. Попробуйте встроенную в Firefox тему "Compact Dark" (если её нет в списке (Firefox 52 и старше), нужно установить аддон [Developer Edition theme enabler](https://addons.mozilla.org/en-US/firefox/addon/devedition-theme-enabler/))

**Comment by m-khvoinitsky** [comment]
Возможно, я ошибся и это не связано с "FT DeepDark". Кое-что поправил в ed545c135b42e219c3f115d9e2a8d168d735771c, просьба проверить новую версию (0.6.7, выйдет скоро).

**Comment by RiNoWaR** [comment]
чекбокс появился на версии 0.6.7
