### ISSUE TITLE
Multiple problems with latest update

### ISSUE THREAD

**Issue by steven6282** [m-khvoinitsky/dark-background-light-text-extension#113]
So an update was downloaded for this extension today.  There are multiple problems with this extension now.  It was working fine before the update.  But now it is painfully slow, I can watch the page CSS be updated and it takes 5 to 10 seconds to fully update a page on sites like Amazon.com

It is also crashing very frequently with only a few tabs open.  Definitely a problem with the extension, I couldn't even get to github with the extension enabled, had to disable it just to be able to get here and post this issue report.

All in all this latest update is a step down from how it was behaving before.  Enough so that I"m going to have to see if I can find an alternative dark theme extension.  As this one is atm, it's unbearable to use.

**Comment by FOHelmstetter** [comment]
I'm having the same issues. Switching to any tab with a github URL causes firefox to crash instantly.

**Comment by m-khvoinitsky** [comment]
> There are multiple problems with this extension now. It was working fine before the update. But now it is painfully slow, I can watch the page CSS be updated and it takes 5 to 10 seconds to fully update a page on sites like Amazon.com

The reason is workaround of Firefox [bug 1393022](https://bugzilla.mozilla.org/show_bug.cgi?id=1393022). It's related only to WebExtensions that's why it first appeared in 0.6.0

> It is also crashing very frequently with only a few tabs open. Definitely a problem with the extension, I couldn't even get to github with the extension enabled, had to disable it just to be able to get here and post this issue report.

No, it's a Firefox bug. See #102 for details.

> Enough so that I"m going to have to see if I can find an alternative dark theme extension.

_This is really useful information for me._

**Comment by steven6282** [comment]
> The reason is workaround of Firefox bug 1393022. It's related only to WebExtensions that's why it first appeared in 0.6.0

Hmm weird for the slowness (which is the only real complaint) to be a result of a permissions bug.  Just FYI, there is no slowness with other dark theme light text extensions.

> No, it's a Firefox bug. See #102 for details.

*shrug* doesn't happen with other extensions.  But guess they just don't do things the same way as your extension to run into the firefox bug.

> This is really useful information for me.

It wasn't meant to be useful.  It was meant to express how annoying the slowness and such was.

Regardless, I've currently got Owl installed instead, does the same exact functions without any of the problems currently.  It however has some features that I don't like and prefer your extension to.  I'll check back in a couple of weeks to see if the workarounds / firefox bugs and such are resolved so that yours works normally again.

Thanks!

**Comment by m-khvoinitsky** [comment]
> Hmm weird for the slowness (which is the only real complaint) to be a result of a permissions bug. Just FYI, there is no slowness with other dark theme light text extensions.

It's slow because of workaround. I have to reload all affected stylesheets (that's a reason of slowness) in a way which helps to avoid permission issues.

> shrug doesn't happen with other extensions. But guess they just don't do things the same way as your extension to run into the firefox bug.

Yep, as far as I know, all other add-ons just inject custom CSS. You can try my add-on's "Simple CSS" or "Invert" methods (it can be switched globally in "Global Preferences") — they work in a similar way but have other drawbacks.

BTW, crashes should be fixed in 0.6.4.
