### ISSUE TITLE
Latest Update breaks Nextcloud 12.0.3 functionality.

### ISSUE THREAD

**Issue by Kewjoe** [m-khvoinitsky/dark-background-light-text-extension#114]
Latest update seems to have broken functionality in my Nextcloud instance. I don't see anything other than the menu and i can't click on anything. Nothing works. I tried refreshing, closing/reopening browser, tried in incognito mode. I also tried in a different version of firefox that doesn't have this addon and it worked fine. If I click on "Disable" in the in-app preferences, it still doesn't fix it. I have to disable it completely in the addon menu before things go back to normal.

This is on Firefox 58 Beta 1 with Dark Background and Light Text 0.63

**Comment by m-khvoinitsky** [comment]
Something is wrong with CSP nonce in Nextcloud which is revealed by 8d45cacede9b66e8f2336e55e4784204555458f5. I'll look into this.

**Comment by monk-time** [comment]
@m-khvoinitsky I think it's the same issue with 0.6.4 and bugzilla.mozilla.org, half of buttons in the site's UI simply don't work (even expand/collapse buttons), and there are a ton of errors in the console like "Content Security Policy: The page’s settings blocked the loading of a resource at self" ([here's a full dump](https://pastebin.com/NM6VBe0s)). The issue disappears when I disable the extension.

**Comment by m-khvoinitsky** [comment]
The problem is in a csp-parse library. [Bug reported to upstream](https://github.com/c0nrad/csp-parse/issues/2).
In the meantime I'm going to re implement required functionality by myself — it's very trivial, I've picked a library in the first place because I was hurrying to fix a bug.

**Comment by m-khvoinitsky** [comment]
Fixed in 0.6.6
