### ISSUE TITLE
Bugzilla reply is broken

### ISSUE THREAD

**Issue by CervantesYu** [m-khvoinitsky/dark-background-light-text-extension#118]
I'm on 0.6.4 and this version breaks the reply button on bugzilla.mozilla.org.

STR:
* Open one bug on bugzilla.mozilla.org
* Click "Reply" of a comment

Expected Result:
The comment text should be quoted in the text area element

Actual Result:
Nothing happens

PS. Disable this extension only for bugzilla.mozilla.org doesn't work the bug around. I have to disable the extension completely in about:addons to make the reply button work.

**Comment by m-khvoinitsky** [comment]
Duplicates #114. Fixed in 0.6.6.
