### ISSUE TITLE
seeing all black pages

### ISSUE THREAD

**Issue by wolftune** [m-khvoinitsky/dark-background-light-text-extension#120]
On Paypal for example. Loads sometimes, sometimes loads, delay, then all black. Disabling DBLT entirely fixed the trouble.

**Comment by FFG-Blinkenn** [comment]
Can confirm, Noticed this problem 3 days ago with paypal. Only site I've had issues with though.

**Comment by m-khvoinitsky** [comment]
Fixed in 0.6.6
