### ISSUE TITLE
Stylesheet processor bad work at some sites

### ISSUE THREAD

**Issue by RiNoWaR** [m-khvoinitsky/dark-background-light-text-extension#121]
It does not fully apply style overlay on ixbt.com

Не полностью применяется наложение оформления стилей на сайте ixbt.com

![v0 6 4_ixbt](https://user-images.githubusercontent.com/33617286/32877852-dc4ba30a-cabc-11e7-9686-d4d141192e7f.jpg)

**Comment by m-khvoinitsky** [comment]
Похоже, более не актуально.
