### ISSUE TITLE
Widescreen issue - topbar not all black

### ISSUE THREAD

**Issue by pdc77** [m-khvoinitsky/dark-background-light-text-extension#122]
Hi there,

Great addon, and essential for me now.  Work in IT and get huge eyestrain at the end of the day when looking at bright pages all the time.

Thankyou very much for taking the time to write this

I have an Ultra Wide Screen monitor though - 3440 x 1440 and the topbar does not all appear as being black.  Are you able to extend your addon to cover it?  Have uploaded a screengrab to show what i mean.

Thanks, Paul
![image](https://user-images.githubusercontent.com/33718564/32886759-9d3424ce-cab9-11e7-846a-acaf188ea6bd.png)

**Comment by m-khvoinitsky** [comment]
Hi.
My add-on doesn't touch Firefox UI at all. It's a Firefox bug.
You can try to enable Firefox' "Compact Dark" theme.

**Comment by pdc77** [comment]
Ah yes, apologies i thought it was all in you addon.  Compact Dark corrects for me

Thanks again for the addon
