### ISSUE TITLE
Breaks image width

### ISSUE THREAD

**Issue by bunnybooboo** [m-khvoinitsky/dark-background-light-text-extension#124]
As seen at https://blog.mozilla.org/firefox/introducing-firefox-multi-account-containers/
Images go full width making articles much harder to read.

**Comment by jtwill** [comment]
I have the same problem on the page linked by the OP. "default" mode of 0.6.6 DBaLT, Firefox 57.0.2 (64 bit) on Windows 10.

**Comment by m-khvoinitsky** [comment]
Fixed in dba08836597ffeb4609f88592dbe0bacabe886f2, same issue as #138 and #145
