### ISSUE TITLE
Issue with google maps

### ISSUE THREAD

**Issue by narkshark** [m-khvoinitsky/dark-background-light-text-extension#128]
First time commenter. I am having a problem with google maps. The map is black no matter what, and I can't figure out how to disable or change this addon's settings for the actual map itself. It used to work just fine.

**Comment by m-khvoinitsky** [comment]
Provide some webpage examples where it reproduces. It works for me on maps.google.com.

**Comment by narkshark** [comment]
I tried it again today and now the map shows up likes it used to. If it happens again I will try to go further into documenting the details.
