### ISSUE TITLE
Facebook messaging doesn't come up?

### ISSUE THREAD

**Issue by XCalibreKris** [m-khvoinitsky/dark-background-light-text-extension#129]
When wanting to message through facebook the box for the chat doesn't come up, it scrolls the web page down a little and doesn't bring the chat up. Am i the only one dealing with this?

**Comment by XCalibreKris** [comment]
Note- i'm using inverted for facebook.

**Comment by m-khvoinitsky** [comment]
It's a Firefox bug, see #126 for details.
