### ISSUE TITLE
Minimize delay in delivering preferences to content script to avoid white flashes

### ISSUE THREAD

**Issue by m-khvoinitsky** [m-khvoinitsky/dark-background-light-text-extension#133]

**Comment by fabeit** [comment]
Really like the add-on because it's customizable, instead of Owl which doesn't let you pick the colors. Unfortunately the white flashes or slow response made me disable the extension. It's quite visible in some sites, even google which people use a lot. Is there anyway to copy the behavior of Owl?

**Comment by m-khvoinitsky** [comment]
#131 is about reducing flashes (this issue is about one particular reason of that complex issue).

I suppose Owl uses something similar to my add-on's "Invert" mode. You can try it. But it has same drawbacks — you can't choose colors.
