### ISSUE TITLE
Broken on Chromium Gerrit (other gerrit instances?)

### ISSUE THREAD

**Issue by m-khvoinitsky** [m-khvoinitsky/dark-background-light-text-extension#137]
https://chromium-review.googlesource.com/c/chromium/src/+/765642

**Comment by m-khvoinitsky** [comment]
`document.styleSheets` almost all time returns zero stylesheets on gerrit.

**Comment by opusforlife2** [comment]
@m-khvoinitsky Has the situation changed over the years? The [LOS Gerrit](https://review.lineageos.org/) is also light-themed on `Default` and all other options. I have to select `Invert` for it to become dark.

**Comment by m-khvoinitsky** [comment]
Looked into it freshly: gerrit uses [Polymer](https://www.polymer-project.org/) which uses [Shadow DOM](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_shadow_DOM) heavily — that's why most stylesheets aren't in the `document.styleSheets` — they're in their own `shadowRoot.styleSheets`. Unfortunately, there is no way to easily enumerate shadowRoots, however, it's possible to inject our implementation of `Element.prototype.attachShadow` (using [exportfunction](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Sharing_objects_with_page_scripts#exportfunction)) which would store all shadowRoots for us.

I've tried implementing it and basically it works good but not flawless:
* Page refresh is needed to process the page after enabling or installing the add-on or after cold browser start — currently no known way to fix this, but as long as not so many websites use it, it's not a big deal.
* Performance — on Chromium gerrit there are more than 1000 shadowRoots which takes some time to process (about a second or two but it's still noticeable).

I'll try to polish it a bit and release with the nearest update.

**Comment by opusforlife2** [comment]
Awesome! Thanks for working on it!
