### ISSUE TITLE
[Request] - Invert all pdf files option

### ISSUE THREAD

**Issue by tigerjack** [m-khvoinitsky/dark-background-light-text-extension#139]
As per the title, I'm wondering if there is the possibility to use a default behavior for the pdf files opening directly in Firefox. At the moment, I've to manually change the behavior to "invert" for each of them.

**Comment by m-khvoinitsky** [comment]
It's a bit ugly but possible. There is another problem. Since Firefox 60 it's not possible for add-ons to process pdf.js pages at all:
https://discourse.mozilla.org/t/extensions-on-pdfjs-pages/28441
https://bugzilla.mozilla.org/show_bug.cgi?id=1456485
