### ISSUE TITLE
page flickers in and out between content and blank page

### ISSUE THREAD

**Issue by jtwill** [m-khvoinitsky/dark-background-light-text-extension#14]
I just found a web page that the dark background light text plugin has
trouble with:

http://www.anuncommonlab.com/articles/how-kalman-filters-work/

For some reason, the page keeps flickering in and out, between the
page and a blank screen. I have never seen this behavior on any other
web page with your plugin. I set the option to "disabled" and the
flickering went away.

**Comment by m-khvoinitsky** [comment]
It works for me. Both on desktop and android. Which method of changing page colors do you use? OS? Desktop/Android? Screencast may help to reproduce it too.

**Comment by jtwill** [comment]
I tried all the methods. Desktop, WIndows 7.

It seems the problem only occurs while the page is still loading. It is a very long page with lots of images, and takes almost a minute to load for me. Even though the problem does not occur during page loading if I disable Dark Background Light Text, I guess there is not much that can be done to stop DBLT from causing the flickering during loading.

**Comment by m-khvoinitsky** [comment]
@jtwill, if the issue is still occurs, can you record a screencast of it?

**Comment by m-khvoinitsky** [comment]
Can't reproduce.
