### ISSUE TITLE
Request: creating white/blacklist for websites to switch to dark mode

### ISSUE THREAD

**Issue by TheRWS96** [m-khvoinitsky/dark-background-light-text-extension#140]
Hello Mikhail Khvoinitsky

I like your extension but i was wondering if you could add a function for people like me who like to only switch certain sites to dark mode.

Most sites i am just fine with the default stile but when i am reading a lot at a site i would like to be able to turn on the extension just for that site (white-listing it)

Then there are also probably people that would like to have the extension on by default and only turn it off for certain sites (black-listing them)

Whether or not you will add this function, i would like to thank your for creating this simple but useful tool. 

With kind regards

TheRWS96

**Comment by m-khvoinitsky** [comment]
It's possible right now. You can choose "Disabled" in "Default method of changing page colors" in "Global Preferences" and then just choose "Stylesheet Processor" only for websites which you want to change colors in.
