### ISSUE TITLE
Firefox Android: please remove icon from address bar

### ISSUE THREAD

**Issue by ghost** [m-khvoinitsky/dark-background-light-text-extension#141]
Please remove the 'Aa' icon from the address bar in Firefox for Android? It takes to much space on smaller devices. There is already an item in the ☰ menu and that is the preferred method. An option to turn it on/off is also an idea.

**Comment by minimalz** [comment]
Seconded.  This the only issue with this addon on Android.

**Comment by gaydenko** [comment]
There are three of us.

**Comment by m-khvoinitsky** [comment]
Removed in the new Firefox for Android.
