### ISSUE TITLE
Hot Keyboard Shortcut to Enable and Disable?

### ISSUE THREAD

**Issue by lgjmac** [m-khvoinitsky/dark-background-light-text-extension#147]
This is a great addon.
Is it possible to bind a keyboard shortcut to turn it on and off?
It obviously has a bit of trouble with some common websites, (off the back of my head amazon cloud reader, and mostly cloud storage) but a few others.
This functionality would be a great add especially if you only want it on for sites that are difficult to read.

**Comment by m-khvoinitsky** [comment]
duplicate of #3
