### ISSUE TITLE
at v0.6.7 image show as blank frame with method "stylesheet processor"

### ISSUE THREAD

**Issue by RiNoWaR** [m-khvoinitsky/dark-background-light-text-extension#148]
at v0.6.7 image show as blank frame with method "stylesheet processor"

при использовании метода "stylesheet processor" на версии 0.6.7 картинки на страницах не отображаются, вместо них пустые рамки с цветом выбранного фона.
пример ниже

**Comment by RiNoWaR** [comment]
![0 6 7 stylesheet processor](https://user-images.githubusercontent.com/33617286/35218131-e703dc50-ff86-11e7-8fac-f05a6bd9b50a.png)

**Comment by RiNoWaR** [comment]
если выбрать "simple css" такой проблемы нет, но часть оформления начинает выледяться "свечением"
![0 6 7 simple css](https://user-images.githubusercontent.com/33617286/35218214-3d444dd4-ff87-11e7-96ac-75e7ee98d8e8.png)

**Comment by m-khvoinitsky** [comment]
Это регрессия после починки #108. Нужно будет улучшить эвристику обработки элементов с inline стилями.

**Comment by m-khvoinitsky** [comment]
Откатил фикс в v0.6.8, нужно будет над ним ещё поработать в #151.
