### ISSUE TITLE
old fox

### ISSUE THREAD

**Issue by csxepx** [m-khvoinitsky/dark-background-light-text-extension#149]
Aaahhh, old (xp) fox colors crazy again... please, this is an ONE & ONLY NORMAL, like it must be, add-on.
Nothing so far can replace it. Sad but true. 👍 :)

**Comment by m-khvoinitsky** [comment]
Please, provide more details. What is wrong (provide some screenshots), which version of Firefox, which version of the add-on?

**Comment by csxepx** [comment]
fox for xp/32, 52.5.3 ESR. Ooops, sorry, i am crazy mf.
![fox](https://user-images.githubusercontent.com/27341410/35259116-519a65c0-001d-11e8-8363-5a51c127f729.jpg)
