### ISSUE TITLE
Mailchimp.com inherits colors in email content when it shouldn't.

### ISSUE THREAD

**Issue by Shickmo** [m-khvoinitsky/dark-background-light-text-extension#152]
I am running the latest version of Firefox on Pop OS, basically Ubuntu 17.10. When I login to mailchimp and create a new email campaign when I use a saved email template and enter the edit mode the theme colors from the addon are automatically saved when I save the email template.

The workaround is to disable the addon and go fix the colors and resave the template. Wanted to open this to see if there was anything you may be able to do on your side of things to offset the issue.

Worth noting I didn't seem to have this issue before the port to webextension format.

Thanks for the awesome addon.

**Comment by m-khvoinitsky** [comment]
https://github.com/m-khvoinitsky/dark-background-light-text-extension/issues/153#issuecomment-766337830
