### ISSUE TITLE
Make the extension easier to find (associate it with "night mode","invert colors")

### ISSUE THREAD

**Issue by tykonin** [m-khvoinitsky/dark-background-light-text-extension#155]
This extension currently gives the best results, especially if we talk about web sites which use Mathjax (Stack Exchange, the "math side" of Reddit...)  
But, it's rather hard to find. Maybe adding some keywords to the description will help, I don't know how the Mozilla's search engine works.

**Comment by m-khvoinitsky** [comment]
Currently it has following words added as "tags": accessibility, black, color, contrast, dark, firefox57, high, jetpack, night, night mode, white (it seems that some of them were added automatically).
It looks that tags are indeed considered during search but with the lowest priority, unfortunately.
I don't really want to add a bunch of SEO-keywords to title. Probably, description would do better, I'll try.

**Comment by m-khvoinitsky** [comment]
UPD: no idea actually how to add keywords to description in a way which won't look like SEO shit.

**Comment by tykonin** [comment]
> UPD: no idea actually how to add keywords to description in a way which won't look like SEO shit.  

Fair enough, I also like things to be simple and to the point (which the current description is).    

BTW. Many thanks from me and my friends for the extension and the time you spend on it!  
I'm gonna close this since it's not software issue.
