### ISSUE TITLE
pageAction should not be visible on desktop

### ISSUE THREAD

**Issue by gybfefe** [m-khvoinitsky/dark-background-light-text-extension#156]
On Mozzilla Firefox Dev Edition

**Comment by m-khvoinitsky** [comment]
Works for me. Provide additional details like exact Firefox version, OS and screenshot which demonstrates the issue.

**Comment by m-khvoinitsky** [comment]
I see. This is a page action which is made for Firefox for Android, on desktop it's not used (should not be visible). Meanwhile, browser action is seems to be hidden. Try to right click on toolbar, then "Customize" and try to find icon there.

**Comment by gybfefe** [comment]
Thank you

**Comment by m-khvoinitsky** [comment]
There is still an improvement needs to be done, updated title, reopening.
