### ISSUE TITLE
Issue with Domains that use Unique Prefixes

### ISSUE THREAD

**Issue by EnsignEpic** [m-khvoinitsky/dark-background-light-text-extension#158]
Basically, every website that uses its own prefix for specific subdomains requires its own rules to be set up on a per-prefix basis. While this may be useful for some websites that use different backgrounds for different subdomains, it's generally a nuisance. The best way to fix this would be to allow users to manually edit any entries in configured pages as opposed to only being able to delete them. That way, you let the user decide if this is a benefit or a detriment on a per-site basis. Examples where this can be seen include Bandcamp, Deviantart, and Yahoo.

**Comment by m-khvoinitsky** [comment]
If you mean different preferences for domains like aaa.example.com and bbb.example.com, you can choose "example.com" in "Dark Background and Light Text options for:" dropdown in pop-up. Is it what you mean?

**Comment by EnsignEpic** [comment]
Yep, that's entirely what I meant. Was not even aware that it was a context menu. Not so much a functional issue as an unclear feature then, my bad!
