### ISSUE TITLE
Main UI gets inverted permanantly

### ISSUE THREAD

**Issue by nhumrich** [m-khvoinitsky/dark-background-light-text-extension#16]
I use the Developer Edition theme.  For some reason, simply installing this extension inverts the entire UI with this theme. 
Here is the trick: for some reason, the add on sets it back to normal so you almost dont notice. However everytime on startup, the ui is all white (its typically black/blue) until this extension loads. 
If you disable or uninstall this add-on, the UI never gets set back, so you are stuck with a white UI forever. The only way I have found to fix this is to use the firefox "refresh" feature which removes all storage for all add-ons/sites.

**Comment by m-khvoinitsky** [comment]
Do you use Firefox Developer Edition or just regular Firefox with add-on "DevEdition theme enabler"?

There are actually two developer edition themes: light and dark. You can switch between them in devtools settings:

**Comment by nhumrich** [comment]
Ah ha. Thanks much.
