### ISSUE TITLE
Provide explanation why "Override the colors specified by the page with your selections above" is incompatible with the add-on on bad_browser_settings.html page

### ISSUE THREAD

**Issue by Gubith** [m-khvoinitsky/dark-background-light-text-extension#161]
Issue - Relentless popup warning about incorrect settings. 
Firefox - 58.0.2 (64-bit) Quantum
System - Windows 10 64 (10.0.16299 Build 16299)

I use High Contrast color override -- it makes about pages dark too!

An error pops constantly, it links to _moz-extension://6415fdae-cef9-40b9-8421-87ca3d23c5d2/ui/bad_browser_settings.html  with instructions to set Firefox Preferences -> Menu -> Preferences -> General -> Language and Appearance -> Colors... -> Override the colors specified -> Never

My path is Tools -> Options -> Language and Appearance: Colors... -> Override the... -> "Only with High Contrast themes"

I set it to "Only with high contrast themes" which has worked well for quite a while now.

BTW this addon is the best, thanks.

**Comment by m-khvoinitsky** [comment]
The problem is when you're using High Contrast theme + "Only with High Contrast themes" or just whatever with "Always", it doesn't make much sense to use my add-on at all. Just choose colours you like in the same preferences dialog.

**Comment by m-khvoinitsky** [comment]
Speaking about internal browser pages, it's possible to paint them using userContent.css, I have plans to build a generator of userContent.css into the add-on with user configured colors (same as Simple CSS). If, for whatever reason, you want to keep using my add-on with "Override the colors specified by the page...", as a workaround, you can keep tab with ".../bad_browser_settings.html" open to get rid of notification.

**Comment by Gubith** [comment]
High Contrast DOES override the addon!  ha!    I use FF on this PC with HC for just for a few specific sites... I'll disable HC and look into uerContent.css again.  I use various computers and try to minimize the amount of effort configuring things, so it'll be much easier with the generator.   Thanks!

**Comment by m-khvoinitsky** [comment]
I guess, some clarification should be written on bad_browser_settings.html page.
