### ISSUE TITLE
All the settings are tiny little bars jammed up to the top right of the screen

### ISSUE THREAD

**Issue by Occams-Cat** [m-khvoinitsky/dark-background-light-text-extension#163]
If I click on OPTIONS to set the different colors, all I get are 3 stacks of thin bars jammed up into the top right of my browser window that I can click on, but it doesn't show what screen element is which, because each bar is only a pixel or two tall

**Comment by m-khvoinitsky** [comment]
Please, provide your browser, OS versions, screenshots. Did it work before? If so, what happened? Have you tried to reset page zoom (Control/Command + 0)?
