### ISSUE TITLE
Breaks facebook in a whole bunch of ways. (Firefox Quantum)

### ISSUE THREAD

**Issue by sclient** [m-khvoinitsky/dark-background-light-text-extension#166]
First off, I really love this addon, it is one of the few that actually manages not to hide some text here or there, and Ive gone through a crap ton of different ones.

On facebook the top bar and the left and right side bars will scroll with the page instead of floating down (I even tried forcing the top bar with FBP, and yes I disabled all my other FB addons to narrow it down to this one during testing). Also the chat window will not render on screen.

Rally hoping there is a solution in the future. Going to have to keep hunting addons for now, sadly, as FB is the main page I wanted dark.

Edit: It actually looks as though only the invert mode causes this, and that mode manages to hide less random texts.

**Comment by m-khvoinitsky** [comment]
Hello. See  #126.
