### ISSUE TITLE
Site is shown approx. 0,5sec-1sec without css at all 

### ISSUE THREAD

**Issue by mitvitaminen** [m-khvoinitsky/dark-background-light-text-extension#171]
Hi,
first of all I wanted to state that this is the best addon ever. It really saves my eyes.
secondly I would like to report a bug. The addon shows me the page completly without css for a very short duration. This is with stylesheetprocessor enabled only.  Is this a firefox internal bug? Does not happen with Firefox addon stylish styled pages though.
Or is this a Bug only locally on my machine? I am on an Arch Linux system.

I like to contribute since I am programmer, where should I take a look? Please hint me to the depending files, would be appreciated.

best regards
Chris

**Comment by m-khvoinitsky** [comment]
This is caused by #96 (Firefox bug) workaround. Stylesheets are needed to be removed, then re-added with different (data:) urls.
