### ISSUE TITLE
Filter "invert" scrolls page to top

### ISSUE THREAD

**Issue by private-lock** [m-khvoinitsky/dark-background-light-text-extension#173]
Hello!

Steps to reproduce:

1. navigate to https://en.wikipedia.org/wiki/Negative_(photography)#Negative_image
2. change filter to "invert"
3. Ctrl+L & Enter will guarantee the page is scrolled to the headline "Negative image" some way down.
4. reload page with F5
5. After reload the page momentarily shows the correct position (good).
6. But after a short delay it will scroll to top (bad).

None of the other filter-modes suffers from this.

Reading through the issue tracker:

- #142 seems different, as in my case the page is absolutely fine and usable, it only starts at the wrong offset.
- #123 mentions the page being scrolled down, but it also features parts of the site being misplaced whereas this is only about the scrollposition.

**Comment by m-khvoinitsky** [comment]
I've tried several times but I can't reproduce it. Can you reproduce it with clear profile? Which OS and Firefox versions?

**Comment by private-lock** [comment]
Sorry for the delay, this one was really tricky to reproduce. I had to dismantle my productive FF-profile piece by piece until only the bug remained ... Now I can build it up from scratch in a fresh profile:

1. Running Kubuntu 17.10
1. stop Firefox if running
1. delete or rename ~/.mozilla/ if available -> will be recreated
1. start Firefox 61.0 (64-Bit)
1. install https://addons.mozilla.org/de/firefox/addon/load-progress-bar/ -> 0.9
1. in another TEST tab load https://en.wikipedia.org/wiki/Negative_(photography)#Negative_image
1. CYCLE: goto Test-Tab, Ctrl+L, Enter (scrolled down), F5 -> still scrolled down GOOD
1. install https://addons.mozilla.org/de/firefox/addon/dark-background-light-text/ -> 0.6.8
1. CYCLE: goto Test-Tab, Ctrl+L, Enter (scrolled down), F5 -> still scrolled down GOOD
1. enable invert-mode for wikipedia
1. CYCLE: goto Test-Tab, Ctrl+L, Enter (scrolled down), F5 -> scrolled up to top BAD

It seems I got lost between enabling and disabling all those add-ons (currently 68 active ...) I missed this configuration disabling only one add-on at a time, I only identified yours, while I should have seen another hit with the progress-bar. Well it was too far down the list to keep up a stern discipline after I thought I already nailed the bug in your add-on.

**Comment by m-khvoinitsky** [comment]
I've reproduced it.
It most likely that it's Firefox bug. In case of Invert, my add-on don't use scripts, it's only CSS. Firefox has some bugs with filters, see #126.
By the way, why do you need this Load Progress Bar? Its informational content is near zero: it's impossible to determine whether there is a lot of page resources left to load or not. Firefox used to experiment with such progress bars on the top of tab but dropped it for the same reason (they have something like this on the mobile though): you can't know the total amount of resources to load until you load all of them. Their loading icon inside tab is the best you can have for the web, unfortunately.
