### ISSUE TITLE
configuration is  inverted

### ISSUE THREAD

**Issue by uvwild** [m-khvoinitsky/dark-background-light-text-extension#174]
I think the use case is rather to enable it on some sites, instead of enable it globally and disable it on specific sites. 

The configuration feels inverse and turns out to be more tedious than it needs to be. 
I believe the real use case would be to try and opt in
- instead of opting out for all the sites I need wot work with in their own design.

I cannot use the extension where I need it. I have to use it and can say where not.

I want to be able to say I want to use it here, but not by default!
This feature is missing badly! and i think its just a few lines of code..

I couldnt find a setting for off by default. only completely disabled
Or I am too stupid to find the right button?

Or maybe there is a fork of this doing that already?

otherwise nice and useful plug! The balanced dark desktop is a real challenge ;)

**Comment by m-khvoinitsky** [comment]
If you want to have an add-on enabled only for certain explicitly chosen websites:
* Go go "Global Preferences", set "Default method of changing page colors" to "Disabled"
* Choose "Stylesheet processor" for websites you want in a pop-up.

Have I answered your question?
