### ISSUE TITLE
Addon is broken in newest nightlies

### ISSUE THREAD

**Issue by CaptaPraelium** [m-khvoinitsky/dark-background-light-text-extension#175]
FF 62.0a1 (2018-06-07) (64-bit)
Win10
Please let me know if I can supply any information to get this working in new versions!

**Comment by PaulBone** [comment]
I'm also getting a problem where the addon works for about half a day, then stops working for new tabs.  Restarting the browser fixes it.

FF 62.0a1 (2018-06-07) (64-bit)
Linux Mint 18.3
Intel Sky Lake integrated graphics.

**Comment by PaulBone** [comment]
Haven't had a problem for a few days now.  I guess something regressed in Firefox and been fixed.

**Comment by CaptaPraelium** [comment]
Yeh can confirm. I was concerned that they were changing something in new versions that broke the addon, but apparently it was just a bug. I'll close this now.

**Comment by m-khvoinitsky** [comment]
> I guess something regressed in Firefox and been fixed.

Looks like. Not #162 and it's good.
