### ISSUE TITLE
Facebook posts visualization error 

### ISSUE THREAD

**Issue by alesmuc** [m-khvoinitsky/dark-background-light-text-extension#177]
Open a Facebbok page with a post like this one

https://www.facebook.com/groups/113888565451701/permalink/1007791306061418/?comment_id=1011634532343762&notif_id=1528899718827118&notif_t=group_comment      

and then scroll down to the last comment. The page will jump up and down

**Comment by m-khvoinitsky** [comment]
It's closed group, I can't see the comment.

**Comment by m-khvoinitsky** [comment]
Can't reproduce.
