### ISSUE TITLE
night/day switch hack to new feature

### ISSUE THREAD

**Issue by malikbenkirane** [m-khvoinitsky/dark-background-light-text-extension#178]
Hey,

First I want say I like the ideas the extension gave me.

As I wished to switch between dark background during the night and light background during the day
because I want to keep my eyes safe while they are focusing on the screen.
I'm using a variant of solarized colorscheme and I finally written a script to change the colors
either to black or light background in the global preferences panel rather than typing.

[There is][1] the script. I tried to keep it very simple hence there is only the flattened colorscheme now.

Would it be possible to add this feature to the extension. I'm thinking of loading the colorschemes from a common file format (e.g. yaml or json) and  a timetable also in the global configuration.

[1]: https://gist.github.com/malikbenkirane/df7a5b87d1b2ad5a3045ec0a771a2099#file-dark_bg_light_text_hack-js

**Comment by m-khvoinitsky** [comment]
Hello.
I suppose you execute it in the developer console? Yep, it's better than nothing.
Some sort of presets and time-dependent automation is planned feature but I don't know when I finally do this.

**Comment by m-khvoinitsky** [comment]
I've created #182 in addition to #54 and #38. Since this snippet is not usable outside of developer console on preferences page, I'm closing this.
