### ISSUE TITLE
Choosing "Disabled" option degrades some web pages

### ISSUE THREAD

**Issue by jtwill** [m-khvoinitsky/dark-background-light-text-extension#179]
When choosing the "Disabled" option for a web page (Note: _**NOT**_ unchecking "Enabled"), DBLT will still degrade some web pages. I have seen it multiple times but the only example I can remember at the moment is ebay (it happens on a lot of ebay auction pages I have looked at).

Why does DBLT do anything at all when the "Disabled" option is selected?

Attached are a couple screenshots of an ebay auction page, one with the "Default" option selected where all text on the page is visible, and the other one where "Disabled" option is selected and some of the web page text is invisible.

https://www.ebay.com/itm/Energizer-Ultimate-Lithium-AAA-Batteries-8-Count-L92SBP-8-AAA8/332584413282

![default](https://user-images.githubusercontent.com/1356681/41814172-62c57034-76fa-11e8-8eeb-b18516154de1.png)
![disabled](https://user-images.githubusercontent.com/1356681/41814173-67f6ece0-76fa-11e8-8f21-35a2e5a435c7.png)

**Comment by m-khvoinitsky** [comment]
Invisible part is iframe with url https://vi.vipr.ebaydesc.com/ws/eBayISAPI.dll?ViewItemDescV4&item=332584413282&t=0&tid=10&category=50602&seller=chevyrcng&vipguid=312a0aac1640a86c1872d0e5fa675277&excTrk=1&tto=3500&lsite=0&ittenable=true&domain=ebay.com&descgauge=1&cspheader=1&oneClk=1&secureDesc=1
You can disable an add-on for this url too and it will be visible. Handling iframes is hard, that's a problem, yes. For reference: #10 #135
#31 will be done in the next version, so if you choose "<Current Tab>", it should affect all iframes too.

**Comment by jtwill** [comment]
I still do not understand why DBLT does anything at all when the disabled option is selected. Cannot DBLT just leave the page alone? Why is there a difference between choosing the "Disabled" option for a page and unchecking the [Enabled] box? From a user point of view, it seems that both methods should prevent DBLT from changing the page. Also, it seems counterintuitive that the page should look worse when choosing the "Disabled" option than when choosing the "Default" option.

**Comment by Grossdm** [comment]
@jtwill, perhaps what I've done would serve as a work around until there is further development.

I have the *Default* set to disabled.

All the iframes would render with DBLT disabled, as you can see from @m-khvoinitsky's comment which shows that the domain is very different in the iframe.

Just a suggestion.

**Comment by Ilias48rus** [comment]
Its bit not ergonomic for new users, but "Enable" and "Disabled" default behavior is fine. But ! this behavior does not work !, im keeping the extension for it's "invert" option, but its *** to uncheck !each! new site i open, so I'll most possible will remove it if it won't get fixed.
