### ISSUE TITLE
black page for images

### ISSUE THREAD

**Issue by Jan02** [m-khvoinitsky/dark-background-light-text-extension#18]
activates on media display (i.e. when only an image is displayed), creates black and can't see image
version 0.5.5

**Comment by m-khvoinitsky** [comment]
Do you mean black semi-transparent images?

**Comment by Jan02** [comment]
no its doing that for all images, even jpgs

**Comment by m-khvoinitsky** [comment]
Well, that's strange. I'm not experiencing the same issue. 
Does images became visible when you:
* disable add-on for specific website?
* uncheck "Enabled" in add-on's popup?
* disable add-on completely (in about:addons)?

**Comment by Jan02** [comment]
@m-khvoinitsky yes if I disable the add-on, the image displays correctly

**Comment by m-khvoinitsky** [comment]
Please, answer all questions.

Also, which other add-ons do you have installed?

**Comment by m-khvoinitsky** [comment]
@Jan02, any information?

**Comment by m-khvoinitsky** [comment]
User seems gone. Closing because it's not enough information to reproduce an issue.
