### ISSUE TITLE
Broken 'Enabled' checkbox in browser action popup

### ISSUE THREAD

**Issue by amithm7** [m-khvoinitsky/dark-background-light-text-extension#180]
Though it works in 'Global Preferences'

**Comment by m-khvoinitsky** [comment]
The add-on adds nothing to context menu. Provide a screenshot.

**Comment by amithm7** [comment]
i mean the configuration for the current tab menu. The menu the menu which pops up when clicking the extension icon. 

![screenshot from 2018-06-24 15-49-53](https://user-images.githubusercontent.com/7036770/41818163-6f1ea46e-77c6-11e8-8db9-dbc574492ec8.png)

**Comment by m-khvoinitsky** [comment]
Do you have any errors in [browser console](https://developer.mozilla.org/en-US/docs/Tools/Browser_Console)?

**Comment by amithm7** [comment]
My setup:
OS: Debian 9.4 (kernal: 4.9.0-6-amd64) with Window manager i3wm.
Browser: Firefox Dev 62.0b1 (64-bit)

My PR was just a quick hack.

The errors triggered by extension while clicking the checkbox are : 
![1529837722_2018-06-24-16 25 22_1917x75](https://user-images.githubusercontent.com/7036770/41818399-eec9098e-77cb-11e8-91e8-491a79a08988.png)

What i am guessing is that it closes too fast. I even tried `onclick` event. Which results the same.

**Comment by m-khvoinitsky** [comment]
I've tried devedition on archlinux under i3 — it reproduces. I'll try to bisect it.

**Comment by m-khvoinitsky** [comment]
```
The first bad revision is:
changeset:   421613:7ca1fccbe7b7
user:        Luca Greco <lgreco@mozilla.com>
date:        Tue Oct 17 04:12:15 2017 +0200
summary:     Bug 1406181 - Add ExtensionStorageIDB JSM module. r=aswan
```

**Comment by m-khvoinitsky** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1406181#c317

**Comment by SpineEyE** [comment]
Any progress on this? I see the same annoyance on Firefox Nightly, Xfce.

**Comment by SpineEyE** [comment]
Could you release a work-around for this please? It seems like there is no progress on bugzilla.
