### ISSUE TITLE
Displays null domain for file: URLs

### ISSUE THREAD

**Issue by stevenwdv** [m-khvoinitsky/dark-background-light-text-extension#186]
1. Open a `file:///...` URL (or the equivalent `file://localhost/...`);
2. Click the extension icon.

`null` is displayed as the domain, while this should be `localhost`:
![null dropdown](https://user-images.githubusercontent.com/27223270/42242352-da065fbc-7f0d-11e8-9327-970efa3c3266.png)

**Comment by m-khvoinitsky** [comment]
While file:// urls handling is not the perfect one, it definitely should not be "localhost".

**Comment by stevenwdv** [comment]
@m-khvoinitsky I don't really get why it *definitely* should not be "localhost", but I understand why you might want to hide it for this special case; but do keep in mind that `file:///` is just an abbreviation for `file://localhost/` and that `file://some_other_host/` is also possible, see https://tools.ietf.org/html/rfc1738#section-3.10

**Comment by m-khvoinitsky** [comment]
> https://tools.ietf.org/html/rfc1738#section-3.10

Makes sense.

**Comment by mixmastamyk** [comment]
This one has been bugging me too, makes authoring documentation difficult, because I need to disable the extension fully instead of using invert.

Also fails on Linux, if that helps any.

**Comment by m-khvoinitsky** [comment]
Will be fixed in #9.

**Comment by atomGit** [comment]
why no progress on this?

**Comment by mixmastamyk** [comment]
Looks like this was fixed, could someone make a release?
