### ISSUE TITLE
Warning in console: Could not fetch source map browser-polyfill.min.js.map

### ISSUE THREAD

**Issue by stevenwdv** [m-khvoinitsky/dark-background-light-text-extension#187]
Sometimes I get the following warning in the console:
```
Fout bij brontoewijzing: TypeError: NetworkError when attempting to fetch resource.
Bron-URL: moz-extension://749b71cb-d915-4ba7-bdfd-6dcd277a7517/lib/webextension-polyfill/dist/browser-polyfill.min.js
Brontoewijzings-URL: browser-polyfill.min.js.map
```
Translation:
```
Error mapping source: TypeError: NetworkError when attempting to fetch resource.
Source URL: moz-extension://749b71cb-d915-4ba7-bdfd-6dcd277a7517/lib/webextension-polyfill/dist/browser-polyfill.min.js
Source map URL: browser-polyfill.min.js.map
```

EDIT: Apparently you can reproduce this by switching to the Debugger tab in the developer tools and back to the Console tab.

Refreshing the page does not fix the issue, disabling the extension on about:addons does, but after re-enabling it the error returns. Opening the same page in another tab *does* fix the issue for that tab; hence it is not (only) dependent on the file content. This all is without the extension even being set to make pages dark (but the error also occurs in that case).

Browser: Firefox Developer Edition 62.0b4 (64-bits)

# Easy fix:
Please remove the line `//# sourceMappingURL=browser-polyfill.min.js.map` in `browser-polyfill.min.js`.

**Comment by m-khvoinitsky** [comment]
So, I guess you know what is Source Maps and what it made for.
Adding source map itself to release build is not right solution as it's not needed in release build.
Removing mentioned line would require changing browser-polyfill build process or sources which is not right which, by the way, probably will raise a warning in Mozilla's verification process that checksum doesn't match for the known library.
After all, I suspect that you would get the same error on most of the modern websites (for example, on https://getbootstrap.com/ )
So, I'm not sure how to properly fix it.

**Comment by m-khvoinitsky** [comment]
Actually, browser-polyfill.min.js isn't needed in Firefox at all, it's for Chromium (which add-on isn't completely ported to yet). So, I've modified build script so it removes all references to browser-polyfill.min.js and excludes it from final build. This indirectly fixes the issue.
