### ISSUE TITLE
Feature request: Work automatically selected web sites added list manualy and work automatically white background web sites

### ISSUE THREAD

**Issue by darkcity87** [m-khvoinitsky/dark-background-light-text-extension#188]
Awsome add-on thanks.
Can you add this options?
Work automatically selected web sites added list manualy and work automatically white background web sites, other web sites disable.
My English is not good.

**Comment by m-khvoinitsky** [comment]
> Work automatically selected web sites added list manualy and work automatically white background web sites, other web sites disable.
My English is not good.

Unfortunately, I don't understand what do you mean. May be you speak Russian?

**Comment by darkcity87** [comment]
I'm generally like web pages original colors and same pages has night themes that's why i want add-on work only eye-burning web sites.
First reguest: Add-on automatically work only manualy selected web sites but other web sites add-on disable
Second reguest: Add-on automatically work white background pages like google or github but other web pages add-on disable

**Comment by m-khvoinitsky** [comment]
So, about first request: am I right that you want to have add-on generally disabled but be able to enable it only for certain websites? If so, it's possible right now. Go to add-on's Global Preferences, choose "Disabled" in "Default method of changing page colors". Then, you can just choose "Stylesheet processor" in pop-up for the websites you want add-on to be enabled.

I still don't understand what do you mean in second request. You mean automatically detect whether the page is already dark? See #41 in that case.

**Comment by darkcity87** [comment]
First one my bad sorry.
Second one: like other issue but different method automatically detecting white pages.
I understand now detecting pages some difficulties so never mind.
Thanks any way.
