### ISSUE TITLE
causes javascript errors on xfinity.com account page, even when disabled

### ISSUE THREAD

**Issue by teknowill** [m-khvoinitsky/dark-background-light-text-extension#189]
Page: https://customer.xfinity.com/#/?CMP=ILC_myaccount_myxfinity_au 

used firefox in safe mode and it works. 
with extension enabled in FF v50-v61, then unchecked or disabled selected in the extension you get js errors and page is stuck loading.

when enabled, you just get all black and not page 

errors from ff console:
Content Security Policy: The page’s settings blocked the loading of a resource at https://static.cimcontent.net/fonts/latest/Xfinity_Standard/XfinityStandard-Regular.woff2 (“default-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at https://static.cimcontent.net/fonts/latest/Xfinity_Standard/XfinityStandard-Regular.woff (“default-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at https://static.cimcontent.net/fonts/latest/Xfinity_Standard/XfinityStandard-Regular.ttf (“default-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at https://static.cimcontent.net/fonts/latest/Xfinity_Standard/XfinityStandard-LightItalic.woff2 (“default-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at https://static.cimcontent.net/fonts/latest/Xfinity_Standard/XfinityStandard-LightItalic.woff (“default-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at https://static.cimcontent.net/fonts/latest/Xfinity_Standard/XfinityStandard-LightItalic.ttf (“default-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at https://static.cimcontent.net/fonts/latest/Xfinity_Standard/XfinityStandard-Light.woff2 (“default-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at https://static.cimcontent.net/fonts/latest/Xfinity_Standard/XfinityStandard-Light.woff (“default-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at https://static.cimcontent.net/fonts/latest/Xfinity_Standard/XfinityStandard-Light.ttf (“default-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at https://static.cimcontent.net/fonts/latest/Xfinity_Standard/XfinityStandard-ExtraLight.woff2 (“default-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at https://static.cimcontent.net/fonts/latest/Xfinity_Standard/XfinityStandard-ExtraLight.woff (“default-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at https://static.cimcontent.net/fonts/latest/Xfinity_Standard/XfinityStandard-ExtraLight.ttf (“default-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at https://static.cimcontent.net/fonts/latest/Xfinity_Standard/XfinityStandard-Thin.woff2 (“default-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at https://static.cimcontent.net/fonts/latest/Xfinity_Standard/XfinityStandard-Thin.woff (“default-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at https://static.cimcontent.net/fonts/latest/Xfinity_Standard/XfinityStandard-Thin.ttf (“default-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at self (“default-src”). Source: if (window.location.href.indexOf('/invit.... customer.xfinity.com:67
Content Security Policy: The page’s settings blocked the loading of a resource at self (“default-src”). Source: window.iperceptionskey="410f8076-db76-45.... customer.xfinity.com:100
Content Security Policy: The page’s settings blocked the loading of a resource at self (“default-src”). Source: var segMin=0,segMax=9;function setCookie.... customer.xfinity.com:100
Content Security Policy: The page’s settings blocked the loading of a resource at self (“default-src”). Source: document.dispatchEvent(new window.Custom.... customer.xfinity.com:100
Content Security Policy: The page’s settings blocked the loading of a resource at self (“default-src”). Source: var bbScript = document.createElement('s.... customer.xfinity.com:108
Content Security Policy: The page’s settings blocked the loading of a resource at self (“default-src”). Source: !function(){var e=document.createElement.... customer.xfinity.com:116

**Comment by m-khvoinitsky** [comment]
The problem is that this website has two Content-Security-Policy which case I don't support.
For reason why I need to alter CSP headers see #96.
Working on fix.

**Comment by teknowill** [comment]
ok thank you

also posted on their site:
https://support.mozilla.org/en-US/questions/1227547#answer-1138571

**Comment by m-khvoinitsky** [comment]
> dev of https://addons.mozilla.org/en-US/firefox/addon/dark-background-light-text/ points to a potential firefox bug:

The problem is not in this Firefox bug, this Firefox bug almost completely prevents my add-on from working which I have to workaround. And the problem is in one of the workarounds.

The fix will be released in the nearest update.

**Comment by teknowill** [comment]
sorry for misunderstanding, thanks

**Comment by m-khvoinitsky** [comment]
[Version](https://addons.mozilla.org/en-US/firefox/addon/dark-background-light-text/versions/?page=1#version-0.6.9) with the fix has been released.
Thank you for the report.

**Comment by teknowill** [comment]
Can confirm that the page works now, thank you! love this extension btw, really saves my eyes a lot of strain.
