### ISSUE TITLE
 whitelist/blacklist with regex support

### ISSUE THREAD

**Issue by Jan02** [m-khvoinitsky/dark-background-light-text-extension#19]
whitelist/blacklist with regex support

**Comment by m-khvoinitsky** [comment]
I was thinking about it but considered it's demand as very low.

Can you describe your usecases?

**Comment by taye** [comment]
It's currently not possible to add configurations for things like the Devtools, Notifications, UIs for other addons, Firefox UI in HTML which doesn't display the URL (saved passwords for example), etc.

![screen](https://cloud.githubusercontent.com/assets/1679746/20030505/8d481526-a35e-11e6-8f39-7486e3ad48a7.png)

![screen](https://cloud.githubusercontent.com/assets/1679746/20030542/5cfd17f8-a35f-11e6-9d04-b6cdf548c9d5.png)

With custom regular expression matching against the **URL**, we could match against the protocol to enable the addon for only http(s) pages:

```
/^http(s)?:/
```

It could also allow different configurations for different subdomains and sub directories:

```
/^http(s)?:(www.)?google.com/
/^http(s)?:mail.google.com/
/^http(s)?:*google.com[/]maps/
```

**Comment by m-khvoinitsky** [comment]
>  It's currently not possible to add configurations for things like the Devtools, Notifications, UIs for other addons, Firefox UI in HTML which doesn't display the URL (saved passwords for example), etc.

How are regexps related to this problem? What you are talking about is #10 

> With custom regular expression matching against the URL, we could match against the protocol to enable the addon for only http(s) pages:

Is there someone who will ever need this?

> It could also allow different configurations for different subdomains and sub directories:

This is possible right now.

**Comment by taye** [comment]
>How are regexps related to this problem? What you are talking about is #10

With regular expressions, we could easily configure multiple pages including, those that we haven't yet visited, with a single rule. It would also allow white/blacklisting of specific file extensions. A different solution to #10 would be helpful but I can imagine several cases where it would be desirable to blacklist some chrome pages but not others (although one could blacklist all chrome and change chrome styles with `userChrome.css` instead).

>Is there someone who will ever need this?

There's at least two of us in this thread. Regex rules are common in extensions that interfere with page content like ad blockers, style changers and privacy utilities so the feature would almost certainly be used by advanced users of those addons.

**Comment by m-khvoinitsky** [comment]
> A different solution to #10 would be helpful but I can imagine several cases where it would be desirable to blacklist some chrome pages but not others (although one could blacklist all chrome and change chrome styles with userChrome.css instead).

It's possible right now. Well, it's not exposed in UI (that's what #10 is about). For example, to disable add-on for [Privacy Badger](https://addons.mozilla.org/en-US/firefox/addon/privacy-badger-firefox/) you can open any of it's internal pages in a tab, for example, settings: resource://jid1-mnnxcxisbpnsxq-at-jetpack/data/options.html and disable it as for any other website.
Same for [NoSquint Plus](https://addons.mozilla.org/en-US/firefox/addon/nosquint-plus/): chrome://zoomlevel/content/lib/siteSettings.xhtml
So, what additional abilities regexps can bring?
How are regexps significantly better than the current solution? Is there some **real** cases when the current approach doesn't solve your issues?



> > > With custom regular expression matching against the URL, we could match against the protocol to enable the addon for only http(s) pages:

> > Is there someone who will ever need this?

> There's at least two of us in this thread. Regex rules are common in extensions that interfere with page content like ad blockers, style changers and privacy utilities so the feature would almost certainly be used by advanced users of those addons.

I wasn't talking about the regexps but only about protocol matching. Same question for "white/blacklisting of specific file extensions".

Don't get me wrong. I'm really appreciate advanced users. But all your suggested use cases are whether possible with current implementation or barely useful.

**Comment by taye** [comment]
>So, what additional abilities regexps can bring?
How are regexps significantly better than the current solution? Is there some real cases when the current approach doesn't solve your issues?

I guess the biggest advantage would be making rules for pages without having to visit them, but adding an input in the settings page to enter pages without regexps would also work.

**Comment by m-khvoinitsky** [comment]
@taye, how do you know if you need a special rule for the site without visiting it? Well, if you do (assume you've visited it before), is it simpler to go to preferences, type a website into the list of exceptions rather than just opening a website and configuring it via pop-up?

**Comment by taye** [comment]
It probably wouldn't be easier but it would spare my eyse from the initial brightness of the page :).

**Comment by m-khvoinitsky** [comment]
Don't you use dark mode by default on all websites?

**Comment by taye** [comment]
I usually prefer to use the *invert* mode but that turns dark pages bright instead.

**Comment by m-khvoinitsky** [comment]
Well, the last point I want to emphasize. If you have several rules that matches current page, which one to use? Obviously, the most _specific_ one. With current "simple" rules I have pretty [simple algorithm](https://github.com/m-khvoinitsky/dark-background-light-text-extension/blob/b1e09c0bc8ee1c5e83eb022f31ffa81260aeb469/lib/index.js#L137) which can calculate which one is more specific. But what to do with regexps? It turns out to be not trivial if not impossible at all. And then try to imagine how to expose it to UI. Well, the only way I see here is to assume that regexp rules is always more specific than "simple" ones. But how to compare two regexp rules?
So, due to low demand, controversial use cases and hard implementation I'm closing this issue for now.

**Comment by taye** [comment]
All right. Thanks for looking into it and thanks for making this extension!

Il 11 dic 2016 9:21 AM, "Mikhail Khvoinitsky" <notifications@github.com> ha
scritto:
