### ISSUE TITLE
Hotkeys: support firefox 63+ variant

### ISSUE THREAD

**Issue by m-khvoinitsky** [m-khvoinitsky/dark-background-light-text-extension#190]
> secondary modifier (optional). If supplied, this must be either "Shift" or (for Firefox ≥ 63) any one of "Ctrl", "Alt", "Command" and "MacCtrl", which has not been used as the main modifier.

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/commands#Shortcut_values

**Comment by david-beers** [comment]
I'm having trouble with using anything but function keys for hotkeys on Firefox 63.0b11 on Windows 10.

**Comment by m-khvoinitsky** [comment]
@david-beers, is the problem still persist? Which hotkeys have you tried?

**Comment by david-beers** [comment]
It looks like the global toggle works but not the toggle for the present tab. I'm now on Firefox 68.0b9 on Windows 10.

**Comment by m-khvoinitsky** [comment]
> It looks like the global toggle works but not the toggle for the present tab. I'm now on Firefox 68.0b9 on Windows 10.

Have you tried to rebind this action to another hotkey? May be it conflicts with something.

**Comment by m-khvoinitsky** [comment]
Now using Firefox build-in shortcuts preferences.
