### ISSUE TITLE
Suggestion for GitHub Repository

### ISSUE THREAD

**Issue by Grossdm** [m-khvoinitsky/dark-background-light-text-extension#192]
Hello,

I suggest that you put a link the the addon's [AMO Page](https://addons.mozilla.org/addon/dark-background-light-text) in either the README.md file or the description of the repo.

This would be helpful to potential users as well as absent-minded users like myself. :blush:

Regards,
Doug®

P.S.
I do recommend that you use the "generic" AMO URL as I have linked above.
Typically, I find links to US-EN for language, and usually for Firefox desktop only.
This generic version redirects to the appropriate language, platform, etc. :ok_hand:

**Comment by m-khvoinitsky** [comment]
Done.
