### ISSUE TITLE
Suggestion for dark images

### ISSUE THREAD

**Issue by torchlard** [m-khvoinitsky/dark-background-light-text-extension#193]
Please consider enhance ability of processing image in dark mode. For example, normally website would display some images with transparent background and black text. The extension will fail to display any of these images because it convert all background colour of images to black!!!  I think it is not a good idea to treat all images equally in dark mode, since background easily mix with text in image. 

Another problem I found when browsing wikipedia. You can see from below picture below, when I click into image, the top right buttons (close button) disappears !!! You can view two pics for comparison. After checking inspector, I find that because extension set background-image to none.
![screenshot from 2018-08-15 19-42-16](https://user-images.githubusercontent.com/34729728/44146690-611696b2-a0c3-11e8-8bba-e1ca604f8cd5.png)
![screenshot from 2018-08-15 19-44-38](https://user-images.githubusercontent.com/34729728/44146748-b70e24a4-a0c3-11e8-9953-39beeb3d0ba8.png)

### black background:
![screenshot from 2018-08-15 20-11-15](https://user-images.githubusercontent.com/34729728/44147644-7d412808-a0c7-11e8-8bf3-31d9c502055b.png)
### grey background (i used stylesheet processor) :
![screenshot from 2018-08-15 20-10-27](https://user-images.githubusercontent.com/34729728/44147652-85e864c6-a0c7-11e8-93a9-daca6b7f05fb.png)

I have a few suggestions for you. 
1.  Add one more custom color specifically for image background besides the currently 6 colors. I recommend grey color as background for greater compatibility with dark text.
2. Allow background-image to be loaded as designed for buttons at least
3. If possible, it would be great if you expose the css files inside "methods" directory, such as the "base.css", "invert.css" files, so that general users have more control on css styles of individual elements. Sometimes it is necessary to overwrite the extension stylesheet, like in case of "background-image set to none", I cannot revert this operation by stylesheet processor !!!
4. Set pictures with white background to lower brightness (can be global setting) by some rules like "filter: brightness(90%)"
 
Thanks very much. :)

**Comment by m-khvoinitsky** [comment]
The problem is that one rule won't fit all cases. I need to analyze images to make right decision. Related issues: #7, #6.

> Add one more custom color specifically for image background besides the currently 6 colors. I recommend grey color as background for greater compatibility with dark text.

What if there will be gray picture on transparent background? Yes, It's more rare but I'd prefer image processing approach.

> Allow background-image to be loaded as designed for buttons at least

I'm doing some heuristics to decide wether to remove `background-image` or not (some `background-iamge`s need to be removed). Sometimes it fails, unfortunately.

> If possible, it would be great if you expose the css files inside "methods" directory, such as the "base.css", "invert.css" files, so that general users have more control on css styles of individual elements. Sometimes it is necessary to overwrite the extension stylesheet, like in case of "background-image set to none", I cannot revert this operation by stylesheet processor !!!

About the case of background-image, see above, about the rest: use Stylus?
In case of wikipedia buttons, I've improved heuristics a bit in af7c0cf0c5ee1b614293c6622aa263914e8c6d08, it should work properly in the next version.

> Set pictures with white background to lower brightness (can be global setting) by some rules like "filter: brightness(90%)"

#60
