### ISSUE TITLE
settings ignored / not applied for file URI scheme (file:///)

### ISSUE THREAD

**Issue by rdeleonp** [m-khvoinitsky/dark-background-light-text-extension#195]
![settings ignored](https://user-images.githubusercontent.com/20749249/45557211-b15e6900-b802-11e8-8f6e-a5c3177305f8.png)

**Comment by mixmastamyk** [comment]
This one has been bugging me too, makes authoring documentation difficult.

Also fails on Linux, if that helps any.

**Comment by m-khvoinitsky** [comment]
URL parsing and handling is complicated and fails in some uncommon cases like file:// protocol indeed. It needs to be refactored someday. You can workaround the issue by setting preferences for `< Current Tab >` if you need.

**Comment by m-khvoinitsky** [comment]
Will be fixed in #9.
