### ISSUE TITLE
Do not process xul dialogs and xul sidebars

### ISSUE THREAD

**Issue by m-khvoinitsky** [m-khvoinitsky/dark-background-light-text-extension#2]
It behaves faulty if firefox itself has light theme:
![bug screenshot](https://cloud.githubusercontent.com/assets/16675892/14404450/98c73af0-fe7f-11e5-949e-19de26ab5050.png)

**Comment by blackwind** [comment]
Only partially fixed. History sidebar still exhibits the issue, as does Tools > Page Info and many other dialogs.

**Comment by m-khvoinitsky** [comment]
Indeed. Will find more universal solution.

**Comment by blackwind** [comment]
> Only partially fixed. ~~History sidebar still exhibits the issue~~, as does Tools > Page Info and many other dialogs.

This remains the case after v0.5.6.

**Comment by m-khvoinitsky** [comment]
Firefox behavior here differs a bit on different OS. One more attempt.
