### ISSUE TITLE
"Disabled" option not working on online office 365 documents

### ISSUE THREAD

**Issue by MilanGM** [m-khvoinitsky/dark-background-light-text-extension#201]
I want to disable Dark Background & Light Text on office 365 online, but nothing happens when i select that option, I still get dark background. The strange thing is, the "Invert" option works. But I want to do a "Disable".

Here is the example format of the url:
https://efront365-my.sharepoint.com/:x:/r/personal/mlic_eront_com/_layouts/15/doc2.aspx?sourcedoc=%7Ba278ffc5-b007-4e71-9679-82ca94853ebb%7D&action=default
(url contains some personal information that is removed)
edit: the red X in the url is ": x :" (without spaces)

**Comment by DecentMakeover** [comment]
Have you tried going to the global preferences and checking what is the status of office365?is it enabled or not?

**Comment by MilanGM** [comment]
Yes, I have **efront365-my.sharepoint.com** in global preferences marked as "disabled"

**Comment by DecentMakeover** [comment]
Okay , let me check this-

On 15-Dec-2018, at 8:16 PM, MilanGM <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes, I have efront365-my.sharepoint.com<http://efront365-my.sharepoint.com> in global preferences marked as "disabled"

**Comment by m-khvoinitsky** [comment]
This should be fixed in the next version which will be released in a week.
