### ISSUE TITLE
Completely disable DBLT leads to unreadable text in text inputs

### ISSUE THREAD

**Issue by tobiasBora** [m-khvoinitsky/dark-background-light-text-extension#203]
Hello,

First thank you very much for this great tool. I just have an annoying problem with it sometimes: when I disable the application (click on the "A", then untick the top right "Enabled" box), the color of the text in text input is not switch back to normal on some websites. On example is here : [https://www.trainline.fr/support](https://www.trainline.fr/support): try to disable DBLT as explained above, and then go on this website, and open, say, the "Bug chasse/Chasse au bug" item. Then type some text in the "Subject/Sujet" part: the text will remain white on the white background: it's unreadable. On the textarea below "How can we help/Comment pouvons-nous vous aider ?" it's still stranger: when I click on it, the text stay white, but the textarea background becomes dark, even if the plugin is supposed to be disabled.

![image](https://user-images.githubusercontent.com/2164118/49478259-9575cc80-f81f-11e8-9ee9-d553c9a9f81f.png)

Would it be possible to fix that please?

Thanks!

**Comment by m-khvoinitsky** [comment]
While it is possible that add-on affects pages in some way when it is disabled by its internal option, this most likely not the case. The problem here is that website sets form background color to white but doesn't sets its text color to black (which is white because of, I guess, your desktop theme). See https://wiki.archlinux.org/index.php/Firefox/Tweaks#Unreadable_input_fields_with_dark_GTK+_themes

**Comment by tobiasBora** [comment]
Thanks for the link. So it was part of the answer, but I actually already had `browser.display.use_system_colors` set to `false`, and I needed to create a new string named `widget.content.gtk-theme-override` and set it to `Breeze` as explained [here](https://github.com/DmitriK/darkContrast#text-contrast-for-dark-themes). Thank you, and sorry for the noise.
