### ISSUE TITLE
Not able to invert jupyterlab

### ISSUE THREAD

**Issue by DecentMakeover** [m-khvoinitsky/dark-background-light-text-extension#204]
Hi Thanks for your work , 

When i try to invert jupyterlab this is what happens,

![jupyterlabissue](https://user-images.githubusercontent.com/25679895/50042055-5435b600-0084-11e9-9821-44f86b2f937b.png)

Any thoughts?

**Comment by m-khvoinitsky** [comment]
Most likely related to #126.

**Comment by m-khvoinitsky** [comment]
Should be fixed, see #126 for details.
