### ISSUE TITLE
Your firefox extension goes APESHIT when confronted with a high contrast theme!!

### ISSUE THREAD

**Issue by Chillrah** [m-khvoinitsky/dark-background-light-text-extension#206]
I think I've given all the information you need. I'm not versatile in extension creation, and it must be hell having Windows fucking up your creations. Can't you just make your app go idle if it recognizes the signs of a Windows setting making it temporarily without use? I love your extension, and people get tired of high contrast themes pretty fast, at least I do, I wish there was a setting for them to not fuck up my browser experience as much as they do. Good luck and best wishes.

**Comment by m-khvoinitsky** [comment]
> I think I've given all the information you need.

No, You don't. When High Contrast theme is in use, Firefox must be configured to ignore it for web content. That's what the extension should tell you about. If it don't, that's a bug. So, what exactly wrong?
