### ISSUE TITLE
Request: Hide toolbar button option (Android)

### ISSUE THREAD

**Issue by lightfire-nyan** [m-khvoinitsky/dark-background-light-text-extension#207]
As the Android version of Firefox does not allow customisation of toolbar buttons it would be nice to add an option to remove the button.

**Comment by m-khvoinitsky** [comment]
I'd wait until the situation with supported WebExtensions API on rewritten [Firefox for Android](https://play.google.com/store/apps/details?id=org.mozilla.fenix) will be clear.
