### ISSUE TITLE
CSS text-shadow should be processed too

### ISSUE THREAD

**Issue by xphnx** [m-khvoinitsky/dark-background-light-text-extension#21]
A picture is worth a thousand words
Plugin disabled
![rzckmne](https://cloud.githubusercontent.com/assets/4024412/15806706/0221dcac-2b4a-11e6-9e06-6adc979957ff.png)

Plugin enabled
![captura de pantalla_2016-06-05_18-20-15](https://cloud.githubusercontent.com/assets/4024412/15806713/35d6051e-2b4a-11e6-81c1-8a005c9f58df.png)

Zoom in
![captura de pantalla_2016-06-05_18-21-50](https://cloud.githubusercontent.com/assets/4024412/15806718/6cf7601a-2b4a-11e6-8812-389a05cd1e7d.png)

Probably there are some shadows in the original CSS. 

Thanks for this plugin I really love it!

**Comment by m-khvoinitsky** [comment]
>Probably there are some shadows in the original CSS

Exactly. I'm aware of the problem and, yes, it needs to be fixed. I'll update bug title to be more specific.
Thank you.
