### ISSUE TITLE
problem with http header modifying

### ISSUE THREAD

**Issue by atomGit** [m-khvoinitsky/dark-background-light-text-extension#212]
in background-script.js...

```
browser.webRequest.onHeadersReceived.addListener(
    details => {
        try {
            let headers = details.responseHeaders.map(header => {
                if (header.name.toLowerCase() === 'content-security-policy') {
                    let new_values = header.value.split(',')
```

i don't have a full understanding of this, but apparently only **one** extension can modify headers using content-security-policy, after which any other extension that uses content-security-policy will fail to modify headers and which one works is a roll of the dice - apparently this is due to the limited WebExt API

DB&LT is the best 'dark web' add-on i've found and i've tested many, but another extension which is **absolutely vital** to me is uBlock Origin and it needs the functionality that content-security-policy provides

can DB&LT be modified to work without using content-security-policy?

for more info on this, see: [unofficial: the extension csp header modification game](https://github.com/ghacksuserjs/ghacks-user.js/issues/664)

**Comment by m-khvoinitsky** [comment]
I have to modify CSP because of #96 ([bug 1393022](https://bugzilla.mozilla.org/show_bug.cgi?id=1393022)). As soon as Mozilla fix this, I can remove CSP modification but for now it would break a lot of websites modification.
