### ISSUE TITLE
bug with disabled on calendar.google.com

### ISSUE THREAD

**Issue by leminsc8er** [m-khvoinitsky/dark-background-light-text-extension#214]
hello i have problem to set events on https://calendar.google.com.
if i set a event and size the Period of time with mouse i have problem with this firefox extension.
i have disabled (filter on dark-background-light-text) for calendar.google.com but it doesnt work.
if i disable the extension completely it works.
can you fix it?

**Comment by m-khvoinitsky** [comment]
If I understood the reason correctly, it will be fixed in the next version which will be released in a week.
