### ISSUE TITLE
Websites with a google custom search bar apply bad css from a 404 page in dark mode

### ISSUE THREAD

**Issue by JAE-UH** [m-khvoinitsky/dark-background-light-text-extension#215]
Specifically, https://www.google.com/cse/static/style/look/v3/deprecated_default.css which I suspect has gone offline recently. The 404 page has inline stylesheet that restricts width to 390px, this is then applied to the entire page in which the search bar is embedded.  
This happens on https://boost.org and https://doc.qt.io from what I've found so far.
The css seems to be correctly blocked in light mode on account of incompatible MIME type but not in dark mode.

Firefox 67.0 (64-bit)

![image](https://user-images.githubusercontent.com/47386501/58618919-fe686980-82c3-11e9-8343-0c7226f6d840.png)

![image](https://user-images.githubusercontent.com/47386501/58618970-1d66fb80-82c4-11e9-924a-ec8d6ebbdba2.png)

**Comment by m-khvoinitsky** [comment]
Fixed in 5722a5b0bf84de82771beddc90afd2302aa50652.
