### ISSUE TITLE
The extension does not properly work on Youtube

### ISSUE THREAD

**Issue by 0100001001000010** [m-khvoinitsky/dark-background-light-text-extension#216]
I'm using this extension on Brave. Unfortunately, there are bugs that prevent it from being usable on Youtube:
Stylesheet Processor will not make the page dark, but will change the color of links to make them unreadable.
Simple CSS will make the page dark, but will block the progress bar and a large portion of the video whenever it is displayed, and it will make sliding toggles both invisible and unclickable.
Invert inverts the video when I have it fullscreen, but otherwise causes no issues.
Disabled will not undo what is done by the other options. If I load youtube with the extension enabled, I must disable it then reload the page to fix the issues.

I know Youtube has its own dark theme, but it keeps forgetting that I had it enabled and I prefer your extension anyways because it allows me to have it completely black (Youtube's is dark gray). Is it possible to fix or is youtube doing a whole bunch of kludgy non-standard stuff to make it harder to deal with?

**Comment by m-khvoinitsky** [comment]
Brave is Chromium-based, doesn't it?

While there was some intermediate success in bringing Chromium version (see #99), some new features of the add-on make it harder to port to Chromium.
Also, if Google finally forbids blocking webrequest modification, it will be impossible to port (we need blocking webrequest API for [bug 1393022](https://bugzilla.mozilla.org/show_bug.cgi?id=1393022)/ #96 workaround which is also needed for Chromium).

**Comment by m-khvoinitsky** [comment]
BTW, youtube works fine in Firefox.
