### ISSUE TITLE
Dark Background and Light Text warning

### ISSUE THREAD

**Issue by Photophobic** [m-khvoinitsky/dark-background-light-text-extension#217]
Please have the pop-up appear once per session.
Your extension has been a complete lifesaver for me!
I have extremely sensitive eyes and can only use my computer in high-contrast mode (white text on black) together with your extension. Unfortunately, I keep getting a pop-up that makes it difficult for me to work or see what I am doing, since it covers up the relevant areas for most webpages.

**Comment by m-khvoinitsky** [comment]
While I agree that it may be too annoying and might be improved but:
* either follow the recommendations on the page which opens when you click on the notification
* or don't use my extension — it isn't really useful when Firefox built-in high contrast mode is in use

Hint: while the page which opens when you click on the notification is open in a tab, no notification is shown.

**Comment by Photophobic** [comment]
Thank you very much for explaining this. Again, I appreciate your extension very much!
