### ISSUE TITLE
Disable Warning Message

### ISSUE THREAD

**Issue by drjbananas** [m-khvoinitsky/dark-background-light-text-extension#218]
I don't want to disable the Firefox high contrast override while I use this extension. If i disable Firefox's override then I get a white flash on every webpage before the add-on kicks in. This is very annoying. If I use only the Firefox override, the text doesn't change color on some sites. I found that it is best to use the Firefox override with the extension. I'm happy with all the results but the warning message is very annoying. It won't stop unless I disable the Firefox override settings. Is there a a way to stop this message? I am happy with the override doing some things and the add-on doing other things. I don't think it has to be one or the other. They actually work well together

**Comment by m-khvoinitsky** [comment]
For now all you can do is keep the tab with the instructions open.
I'm going to revise this behavior.

**Comment by j77h** [comment]
I was going to ask you to not show the warning popup while the extension is temporarily disabled (from the menu-bar icon), but what you're planning now might make this redundant.

**Comment by iBilley** [comment]
i need such disable warning  option too, i have low vision and need a total dark back ground and this Addon helps alot, but the warnings are a hinder.

**Comment by m-khvoinitsky** [comment]
> Noticed that using Firefox colors override with your extension enabled, there are no colors in google calendar. (maybe in other pages too, but haven't noticed yet)

As I already wrote in https://github.com/m-khvoinitsky/dark-background-light-text-extension/issues/217#issuecomment-521422980, the extension can do little when this Firefox feature is in use and it is barely useful.

**Comment by m-khvoinitsky** [comment]
> i need such disable warning option too, i have low vision and need a total dark back ground and this Addon helps alot, but the warnings are a hinder.

Firefox is doing great progress on implementing dark theme for UI.
