### ISSUE TITLE
[Suggestion] Default values not too "rough" as pure black and pure white

### ISSUE THREAD

**Issue by xphnx** [m-khvoinitsky/dark-background-light-text-extension#22]
What do you think about setting default values for foreground and background to something more "silky"? I propose foreground #D5D5D5 and background #212121, or similar. 

*I am not an english speaker so words inside "" could not be the better.

**Comment by m-khvoinitsky** [comment]
Well, I prefer pure white on pure black. Not sure about majority. It would be better to set default values to such as the majority prefers. But currently I do not have any analytic to determine it.
Also, I have plans to implement sync of settings via Firefox Sync. So, it may help you to avoid additional setup.

**Comment by xphnx** [comment]
It's not for me, it's quite easy to change the values. If you prefer the pure values it's perfect then. xD
