### ISSUE TITLE
Whitelist mode

### ISSUE THREAD

**Issue by ZIEXED** [m-khvoinitsky/dark-background-light-text-extension#227]
The extension currently works by default in all sites unless disabled by specific domain rules Which means it's on the Blacklist mode
Please add the ability to reverse this mode to stay off by default on all sites unless enabled by specific domain rules.

**Comment by m-khvoinitsky** [comment]
This is possible.

Set "Default method of changing page colors" to "Disabled", then for whatever website you want to enable it, set the mode to "Stylesheet Processor".
