### ISSUE TITLE
read and modify browser settings for update

### ISSUE THREAD

**Issue by ZeroMaki** [m-khvoinitsky/dark-background-light-text-extension#228]
so why does it now need to read my browser settings and be able to modify them?

**Comment by m-khvoinitsky** [comment]
https://github.com/m-khvoinitsky/dark-background-light-text-extension/blob/master/lib/background-script.js#L244-L246

Before this change, extension used to check if the preferences are valid (via some indirect data) and **ask** user to fix their preferences. Notification permission was needed for this but it's not needed anymore.
