### ISSUE TITLE
https://www.vanityfair.com/news/2019/12/melania-trump-greta-thunberg

### ISSUE THREAD

**Issue by SeriousHoax** [m-khvoinitsky/dark-background-light-text-extension#229]
Doesn't work properly on this site. Starting of the article is not visible in default and simple css mode.
https://www.vanityfair.com/news/2019/12/melania-trump-greta-thunberg

**Comment by m-khvoinitsky** [comment]
What exactly? Can you provide screenshots?

**Comment by SeriousHoax** [comment]
Here, the texts are not visible. 
![1](https://user-images.githubusercontent.com/29574622/70861383-56607800-1f57-11ea-9973-f7a485d9fdec.png)
![2](https://user-images.githubusercontent.com/29574622/70861384-56f90e80-1f57-11ea-87d1-4166cd2ce653.png)

**Comment by m-khvoinitsky** [comment]
I can't reproduce it. Try it with clean Firefox profile.

**Comment by SeriousHoax** [comment]
I use tools like shadowfox and some about:config tweaks to make things dark so maybe one of those things causing this. Ok, no problem, invert mode will do the job. 
Instead of creating a new issue let me mention something from another site here. The top part is not visible, text on left and the robot image on right. Maybe it's not easy to fix this issue. Other extensions struggle here as well. Some inverts the top part.

https://www.virusradar.com/en/update/info/ 

![1](https://user-images.githubusercontent.com/29574622/70861686-edc7ca00-1f5b-11ea-88ae-74a50395c201.png)
![2](https://user-images.githubusercontent.com/29574622/70861687-ee606080-1f5b-11ea-8014-c9a55ad34537.png)

**Comment by geeknik** [comment]
Invert works just fine on Virus Radar with Firefox 73.0a1:

![Screenshot_2019-12-15 Update Info ESET Virusradar](https://user-images.githubusercontent.com/466878/70863939-40e25280-1f45-11ea-97d9-20907b08fe47.png)

And the Vanity Fair article also looks perfectly fine, must be another extension interfering.

**Comment by SeriousHoax** [comment]
> 
> 
> Invert works just fine on Virus Radar with Firefox 73.0a1:
> 
> ![Screenshot_2019-12-15 Update Info ESET Virusradar](https://user-images.githubusercontent.com/466878/70863939-40e25280-1f45-11ea-97d9-20907b08fe47.png)
> 
> And the Vanity Fair article also looks perfectly fine, must be another extension interfering.

Invert works fine but I was talking about the default Stylesheet processor mode.

**Comment by m-khvoinitsky** [comment]
This is a background image which was removed by Stylesheet processor. It uses some heuristics to decide whether to remove the image or not and, obviously, sometimes it fails. I don't have a good solution to this problem in a short term.
