### ISSUE TITLE
changing default behaviour

### ISSUE THREAD

**Issue by mouarflenoob** [m-khvoinitsky/dark-background-light-text-extension#236]
Hello !

I would like for this extention to not do anything by default, and to manually choose to toggle a website when I decide to.
Is it something I can already do?

Thanks !

**Comment by geeknik** [comment]
Yes, after you install the extension, visit the `Global Preferences` and change the `Default method of changing page colors` to disabled. Then when you visit a page that you want to turn dark, just tap the extension icon and choose the setting you like and it will remember those sites. You can see the list of them on the `Global Preferences` page as well.

**Comment by m-khvoinitsky** [comment]
Thank you, @geeknik.
