### ISSUE TITLE
Certain embedded iframes are made dark even when mode is disabled

### ISSUE THREAD

**Issue by slowriot** [m-khvoinitsky/dark-background-light-text-extension#24]
Example with twitter embeds: ![](https://i.imgur.com/gOYVMge.png) (from the page at http://www.theguardian.com/politics/2016/jun/23/eu-ballot-papers-pencils-conspiracy-fears-social-media-voters)

In this case, my global "Default method of changing page colors" is set to "disabled", and the per-page setting here is default.

**Comment by m-khvoinitsky** [comment]
@slowriot, do you have other examples of this behavior. With your options this page works good.

Other issues may be related to #10 so always try with "Default method of changing page colors" -> "Disabled" as you already did.

**Comment by devoray** [comment]
Example with twitch.tv - I believe it's related. 
Odd behavior in general, as inversion doesn't reach the corner of the player. 
Minimized view shows the issue:
![inverted_embedded_player_small](https://cloud.githubusercontent.com/assets/2679343/21676720/bb173a42-d2eb-11e6-8f2a-aa6338f4667f.png)

Maximized embedded player to show more of the issue.

![inverted_embedded_player_large](https://cloud.githubusercontent.com/assets/2679343/21676742/c86ab494-d2eb-11e6-8aff-ff4b2f5520d2.png)


Embedded player doesn't change style when disabled on twitch.tv
Have to turn off the entire plugin.

**Comment by slowriot** [comment]
@m-khvoinitsky the issue no longer shows for me on the original page either, so something may have changed either with firefox or with the plugin since I posted it; I'll post here if I come across other examples.

**Comment by devalphabeta** [comment]
I am also have problem with IFRAME having black background

**Comment by m-khvoinitsky** [comment]
Can't reproduce both cases (original link with tweets and twitch issue #62). Seems that something has been changed either on my side or on the websites.
@devalphabeta , please, provide more details, make sure that this is not the #10 case (see [previous comment](https://github.com/m-khvoinitsky/dark-background-light-text-extension/issues/24#issuecomment-261747941))
