### ISSUE TITLE
Crashes on Firefox 74.0

### ISSUE THREAD

**Issue by ravsv650** [m-khvoinitsky/dark-background-light-text-extension#243]
It may work for few hours and at some point CPU usage will start going UP and browser stops responding eventually generating a crash pop-up. When add-on is disabled issues is not present.

**Comment by m-khvoinitsky** [comment]
I do not experience anything like this despite I use Firefox 74 for days sometimes.
I recommend you to find your crash [here](https://crash-stats.mozilla.com/) (see [here](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Crash_reporting) for the details) and find out if there is already bugreport in Bugzilla.

**Comment by ravsv650** [comment]
Thank You

Rafal Gromniak
Pozdrawiam
Best regards


czw., 26 mar 2020 o 11:11 Mikhail Khvoinitsky <notifications@github.com>
napisał(a):
