### ISSUE TITLE
option to use whitelist intead of blacklist

### ISSUE THREAD

**Issue by bart9h** [m-khvoinitsky/dark-background-light-text-extension#244]
When this extension is enabled, it works for every site, and I can set an option specific for each site to turn it off, as in a blacklist.

It would be nice to have an option to behave the opposite way: the extension is enabled, but the default is for it to be off, and I can set each site to be on, as in a whitelist.

**Comment by geeknik** [comment]
You can already do this. Go into the `Global Preferences for the extension and set the default mode to `Disabled`. Then on a site by site basis, you can set the site to `Invert` or `Simple CSS` and the extension will remember your settings when you launch the browser next time.

**Comment by m-khvoinitsky** [comment]
> You can already do this. Go into the Global Preferences for the extension and set the default mode to Disabled. Then on a site by site basis, you can click on the extension icon and set it to Invert or Simple CSS or whatever and the extension will remember your setting for that particular site the next time you launch Firefox.

Precisely. However, the default mode is `Stylesheet Processor` so I recommend to use it.

**Comment by bart9h** [comment]
Thank you.
Sorry, I didn't found this option on the Global Preferences.
