### ISSUE TITLE
Bug? Inverted mode kind of breaks mouse scrolling on ProtonMail

### ISSUE THREAD

**Issue by geeknik** [m-khvoinitsky/dark-background-light-text-extension#247]
Inverted mode looks great on ProtonMail, however if I want to reliably use the mouse wheel to scroll through the body of an email, I have to switch over to Stylesheet Processor or only use the mouse wheel while hovering over the scrollbars. Is there anything that can be done here to interfere less with scrolling? I see nothing helpful in the browser console and I have yet to see this behavior on any other sites. Also worth noting, The Dark Reader doesn't interfere with the scrolling on ProtonMail, but that extension is a resource hog. Thank you.

**Comment by m-khvoinitsky** [comment]
I've just tried it and it works well.
The add-on doesn't interfere with scrolling in any way, so it's weird that you experience this problem.
Which OS and browser version do you use?

**Comment by geeknik** [comment]
Fedora 31 + Firefox Nightly 77.0a1 (2020-04-28) (64-bit).

**Comment by m-khvoinitsky** [comment]
Have you tried it in stable?

**Comment by geeknik** [comment]
Of course. 

I am using the ProtonMail layout with the body of the email on the right, the titles of the other inbox entries on the left. This bug doesn’t affect scrolling the left frame, only the right, and never 100% of the time. I can be scrolling along and it just stops after after a few lines and then I have to drag the scrollbar. 

Restarting the browser helps briefly but I leave a tab open for email most of the day so the issue usually returns. Unable to debug further so if you can’t reproduce I’ll close. Thank you.

**Comment by geeknik** [comment]
Also it appears that ProtonMail has a new version in development with a native dark mode, making this whole exercise moot:

`To try dark mode, sign in to your account at beta.protonmail.com and click Settings. Under Appearance, scroll down to Themes, and select "Dark mode". `
