### ISSUE TITLE
Unkown error

### ISSUE THREAD

**Issue by giriannamalai** [m-khvoinitsky/dark-background-light-text-extension#248]
PC:
Ubunut 16.04 - FF 74.0 (64-bit)

Error:
`09:35:17.502 Error: "An unexpected error occurred" background-script.js:129:27

09:35:17.501
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:812
    normalizeStorageError resource://gre/modules/ExtensionStorageIDB.jsm:812
    method chrome://extensions/content/child/ext-storage.js:273
    AsyncFunctionThrow self-hosted:700

09:35:17.525
Error: "An unexpected error occurred" configure-for-current-tab-panel.js:255:33
    <anonymous> moz-extension://496e08ae-9a05-4e4f-9410-c393fda5c0ca/ui/configure-for-current-tab-panel.js:255

09:35:17.525
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:812
    normalizeStorageError resource://gre/modules/ExtensionStorageIDB.jsm:812
    method chrome://extensions/content/child/ext-storage.js:273
    AsyncFunctionThrow self-hosted:700

09:35:17.554 TypeError: can't convert undefined to object shared.js:52:185`
![Screenshot from 2020-05-04 09-39-02](https://user-images.githubusercontent.com/14800472/80935639-2a9d3c00-8deb-11ea-8fa2-3171fd437c1d.png)

No idea how to fix it.

**Comment by m-khvoinitsky** [comment]
Have you tried to reinstall the add-on? Looks like the saved preferences are corrupted.
