### ISSUE TITLE
Remove keyboard shortcut settings from options UI in Firefox

### ISSUE THREAD

**Issue by Gitoffthelawn** [m-khvoinitsky/dark-background-light-text-extension#258]
Setting shortcuts via DBLT's options UI has no effect in recent versions of Firefox.

In Firefox, the best way to change keyboard shortcuts is via "Manage Extension Shortcuts" in the dropdown in `about:addons`.

**Comment by m-khvoinitsky** [comment]
Good point. I was actually going to do this — I'm going to significantly redesign preferences and since Firefox got its own hotkey changing UI — it's much better to just point users to it.
