### ISSUE TITLE
Add-on affects Tree Style Tab even if disabled via menu

### ISSUE THREAD

**Issue by Dioxylin** [m-khvoinitsky/dark-background-light-text-extension#26]
Hello,

The add-on seems to affect Tree Style Tab even if the Enabled is unticked.  If the add-on is disabled through the Add-on menu, it stops inverting the menu.

Not sure what the issue really is.  I'm on Windows 7 using Firefox 47.0.1.
![dblt_tst_interaction](https://cloud.githubusercontent.com/assets/10519985/17483926/84e5c1e6-5d4d-11e6-89af-cb34f100cd48.png)

**Comment by benoit-pierre** [comment]
You need to restart the browser for the change to take effect on chrome elements. You can manually disable the addon for chrome elements by adding `"chrome:":"0"` to the configuration setting `extensions.jid1-QoFqdK4qzUfGWQ@jetpack.configured_pages`.

**Comment by Dioxylin** [comment]
Oh cool!  Thank you!  That works!

Disabling and re-enabling the add-on seems to work instead of restarting after the change.

**Comment by m-khvoinitsky** [comment]
> You need to restart the browser for the change to take effect on chrome elements

Actually, no. If yes, it's a bug. I'll investigate it.

>The add-on seems to affect Tree Style Tab even if the Enabled is unticked. If the add-on is disabled through the Add-on menu, it stops inverting the menu.

Can you clarify this sentence?
* It doesn't affects Tree Style Tab if add-on is disabled completely (through about:addons)?
* It affects Tree Style Tab if add-on disabled trough it's "Enabled" checkbox?
Right?

**Comment by Dioxylin** [comment]
Hmm, on further investigation, I mistyped the setting and this did not fix it (it made the add-on not work completely).  Setting "chrome":"0" did not help.

Your interpretation of the sentence is correct.

**Comment by benoit-pierre** [comment]
You're missing a `:`: `"chrome:"`. I know this prevent the addon from inverting the popups for uMatrix and uBlock in my case, and I know I add to restart for the change to take effect in those cases (but not for things like about:config).

**Comment by Dioxylin** [comment]
"chrome:":"0" also did not work after restarting Firefox.

**Comment by m-khvoinitsky** [comment]
@Dioxylin, what do you mean by "affect Tree Style Tab"? TreeStyleTab's tabbar or TreeStyleTab's settings window?

**Comment by Dioxylin** [comment]
TreeStyleTab's tabbar.  The screenshot given in the original post is depicting the tabbar with the Enabled setting unticked in the Dark Background Light Text add-on.

**Comment by m-khvoinitsky** [comment]
I see.
The problem is that Tree Style Tab theme (light or dark) follows Firefox developer tools theme. Meanwhile, my add-on sets developer tools theme to dark on startup.
You can try:
Menu -> Developer tools -> toggle tools -> Toolbox options icon on the top right corner -> Themes -> Choose "light".
But it will reset back on browser restart.
Currently, there is no way to disable this behavior. That's needs to be fixed.
Let me know if it is what I'm talking about.

**Comment by Dioxylin** [comment]
Hey!  That fixed it!  You're right that it resets on restart, but at least it's a workaround.  Thank you!

**Comment by m-khvoinitsky** [comment]
[#64](https://github.com/m-khvoinitsky/dark-background-light-text-extension/issues/64#issuecomment-303813270)
