### ISSUE TITLE
[Feature request] Add support to PDF opened by Firefox

### ISSUE THREAD

**Issue by Nokia808** [m-khvoinitsky/dark-background-light-text-extension#261]
Hi. It is very needed to activate dark mode on PDF opened by Firefox. But currently no any extension can do this !

It will be very useful - if technically possible - to make dark-background-light-text-extension working & effective on PDF opened by Firefox exactly as it effective on web page.

**Comment by m-khvoinitsky** [comment]
No, it's not possible. Every time when the add-on says "Modification of this page is not available due to Firefox restrictions", it means it, there is no way to workaround it (apart from userContent.css, but, again, add-ons can't edit it).
