### ISSUE TITLE
Doesn't apply to raw.githubusercontent.com

### ISSUE THREAD

**Issue by opusforlife2** [m-khvoinitsky/dark-background-light-text-extension#269]
Try opening any file as raw in Github. It isn't themed by the extension. See also: https://github.com/darkreader/darkreader/issues/943.

**Comment by m-khvoinitsky** [comment]
The add-on clearly describes the reason in its pop-up:
> Modification of this page is not available due to Firefox restrictions

I have nothing to do here.

**Comment by m-khvoinitsky** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1411641

**Comment by opusforlife2** [comment]
Ah, sorry. I forgot to close this after someone clarified this was a Firefox issue.
