### ISSUE TITLE
Apparently this happened

### ISSUE THREAD

**Issue by samiuljoy** [m-khvoinitsky/dark-background-light-text-extension#270]
![Screenshot_2020-07-23-22-07-01](https://user-images.githubusercontent.com/51329626/88310881-0427d680-cd32-11ea-8e39-026c9b03c973.png)
First time seeing this.

**Comment by m-khvoinitsky** [comment]
Is this happening every time on this page? Seems like it's too heavy.
Can you provide full page URL?

**Comment by samiuljoy** [comment]
Well, I was googling for adb device unauthorization and the first link that popped up was this https://support.honeywellaidc.com/s/article/How-to-fix-adb-devices-shows-unauthorized-device&sa=U&ved=2ahUKEwjQ4oPt5OPqAhXRXSsKHZKqBCoQFjAAegQICRAB&usg=AOvVaw2re4yFvNz4FNeUU_lShUoT
and seems like this keeps happening on every visit to this site.
