### ISSUE TITLE
Invert mode adding vertical offset when displaying an image

### ISSUE THREAD

**Issue by EmmaINSA** [m-khvoinitsky/dark-background-light-text-extension#272]
I noticed this bug a few weeks ago : whenever I display an image (JPG or PNG) in a Firefox tab using the "invert" mode of the add-on, it has a negative vertical offset hiding a part of it, but can't be scrolled. The offset seems to be so that only the lower half of the image is displayed.
This doesn't happen with the other modes, or when the add-on is disabled.

I am using Firefox 79.0 (64 bits), on Windows 10, and the 0.7.2 release of the add-on.

Screenshots of the issue : 

Image used : [GitHub logo (png)](https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png)
![inverted_mode_offset](https://user-images.githubusercontent.com/33004979/89631313-e9607080-d8a0-11ea-82be-8583c1e6a101.PNG)
![other_mode_no_offset](https://user-images.githubusercontent.com/33004979/89631343-f2e9d880-d8a0-11ea-8067-84c05e802c0b.PNG)
Image used : [random grid (jpg)](https://onlinejpgtools.com/images/examples-onlinejpgtools/random-grid.jpg)
![jpg_offset](https://user-images.githubusercontent.com/33004979/89631347-f5e4c900-d8a0-11ea-825f-ac052bb1d04d.PNG)
![jpg full](https://user-images.githubusercontent.com/33004979/89631348-f715f600-d8a0-11ea-9627-722e832e56b8.PNG)

**Comment by m-khvoinitsky** [comment]
Try to enable options specified in https://github.com/m-khvoinitsky/dark-background-light-text-extension/issues/126#issue-276778271. That's an old issue (and not the only) with "old" Invert method which is used when `backdrop-filter` is not supported. Please, try and report the result.

**Comment by EmmaINSA** [comment]
It fixed the offset issue, but now the background color is almost white.
I guess this is how the invert mode is supposed to work when the default background color is dark, so it doesn't really matter.
Thanks for your help ! 😄
