### ISSUE TITLE
Extention is not working for local files

### ISSUE THREAD

**Issue by toffler** [m-khvoinitsky/dark-background-light-text-extension#281]
For URLs like:
file:///F:/xxx/xxx/xxx.html
the extension doesn't work, all options in the drop down menu start with "null", like "null/F...", Win10, Firefox 82.
I guess URL.origin is null for local files?

I made it work by adding two lines of code:
in configure-for-current-tab-panel.js turned local path into a fake URL:
```
    async function generate_urls(url_str) {
        url_str = url_str.replace(new RegExp('^file:///([A-Z])?:'), 'http://drive$1.com');
```
and the same in content-script.js:
```
async function get_method_for_url(url) {
    url = url.replace(new RegExp('^file:///([A-Z])?:'), 'http://drive$1.com').toLowerCase();
```

**Comment by atomGit** [comment]
would be nice if the developer fixed this

**Comment by toffler** [comment]
I don't think this addon is maintained anymore, will be faster if you fix it yourself ;)

**Comment by m-khvoinitsky** [comment]
Don't panic. I do not work on the add-on regularly but I do fix severe issues when they pop out.

Old URL handling code was a big pile of mess, suggested fix with fake domain seems to work only on Windows.
Likely, finally I managed to find time to refactor this code. It took quite a while: I refactored the whole add-on to use webpack which allowed me more easily include third-party library for TLD handling like it used to be with Add-on SDK, the code is now shared between content script and panel and now it properly handles many corner cases like IP, IP:port, IPv6, IPv6:port, file/// and so on.

Please, test.

**Comment by atomGit** [comment]
thanks for addressing this and updating the code

i downloaded a zip of the repo and tried loading the ext in FF v84 from about:debugging but got an error: "dark-background-light-text-extension-master.xpi does not contain a valid manifest"

i'm not seeing anything wrong with the file

**Comment by m-khvoinitsky** [comment]
The add-on source code on its own is no more usable for loading into Firefox directly (for a while, actually).
You should execute in the extracted add-on directory:
```
npm install
./build
```
Then you can load either build.xpi or ./dist directory into Firefox.

**Comment by atomGit** [comment]
i don't have npm installed, but i extracted the zip and pointed FF to the manifest and it loaded, however the icon context menu and settings page just said 'Loading...'

ill wait until it's published on AMO, no problem

**Comment by toffler** [comment]
I have npm but I can't execute bash scripts on Windows or set up Ubuntu shell, so I can't test either

**Comment by m-khvoinitsky** [comment]
Well,
```
npm install
npx webpack
```
Then you can load `dist` directory directly to Firefox (in about:debugging).

**Comment by toffler** [comment]
Ok, it seems to work for local files for me now.
Great addon, thanks!

The only persistent issue that I have is that some images disappear on pages like this https://www.w3schools.com/tags/tag_div.ASP in "Browser support" section browser icons becomes invisible.
Also, I often have to manually invert images on pages like so document.querySelectorAll('img').forEach((e)=>e.style.cssText+="filter:invert(100%)"). As a Christmas wish -  it'd be nice to have this option built-in, separately from changing styles.

**Comment by m-khvoinitsky** [comment]
> https://www.w3schools.com/tags/tag_div.ASP in "Browser support" section browser icons becomes invisible.

Fixed this.

>  Also, I often have to manually invert images on pages like so document.querySelectorAll('img').forEach((e)=>e.style.cssText+="filter:invert(100%)"). As a Christmas wish - it'd be nice to have this option built-in, separately from changing styles.

First, website-specific preferences should be implemented (apart from method). Then I can think about it. For now, you can use something like
```css
img {
    filter: invert(100%) hue-rotate(180deg);
}
```
with Stylus and enable it only for pages you need.
