### ISSUE TITLE
"Invert" mode causes severe scrolling lag on the new Firefox for Android (Fenix)

### ISSUE THREAD

**Issue by serovar** [m-khvoinitsky/dark-background-light-text-extension#282]
In the new Firefox for Android Nightly, [you can install custom add-ons](https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/), so I tried installing DBLT. It works perfectly fine with the default "Stylesheet processor" mode, but if you change it to "Invert" mode there is severe scrolling lag on every page.

**Comment by panagiotis94** [comment]
Happens in Firefox Nightly 201130 17:01 (Build #2015778699) too. Everything else works ok except Invert mode.

**Comment by m-khvoinitsky** [comment]
There is nothing I can do here: Invert mode is just a tiny bit of CSS which enables filter which, in turn, completely handled by the browser itself. It is a bit slow even on desktop, and on some mobile devices it may be extremely slow.
