### ISSUE TITLE
some suggestions

### ISSUE THREAD

**Issue by chrimez** [m-khvoinitsky/dark-background-light-text-extension#283]
Love it!  I first cam across "Dark Reader" but that exploded RAM usage, so I found your extension.
My recommendations to the developer: 
1) improve key-word search to find the add-on (compared with "Dark Reader"). 
2) adjust default colors - see "material.io": #121212 and #C3C3C3 for background and text. 
3) Consider extending the color with "opaqueness" to a full RGB-A model. 

Thanks again for this add-on :)

**Comment by Jonta** [comment]
I suggest splitting this into several issues. =)

**Comment by chrimez** [comment]
Ok, there we go...

**Comment by Jonta** [comment]
@chrimez I also suggest linking to the new issues, like so:

#322
#323 
#324 
#325
