### ISSUE TITLE
problem with system messaging of linkedin

### ISSUE THREAD

**Issue by 2EricBrunet** [m-khvoinitsky/dark-background-light-text-extension#284]
Hello,
I notice (from a lot of months) a problem with windows of discussions  into the main web page.
When you scroll, the windows discussion fall down and become not accessible (the timeline of posts is illimited).
Obvioulsy, this issue is resolved if I disabled your plugin.

**Comment by m-khvoinitsky** [comment]
Which method do you use? Invert?

**Comment by 2EricBrunet** [comment]
> Which method do you use? Invert? If so, try the steps from [#126 (comment)](https://github.com/m-khvoinitsky/dark-background-light-text-extension/issues/126#issue-276778271) and check if it helps.

Excuse me that I not answered. This issue is now resolved (modification from linkedin?)
