### ISSUE TITLE
Since version 0.7.6, dark mode doesn't work.

### ISSUE THREAD

**Issue by ArcticGems** [m-khvoinitsky/dark-background-light-text-extension#287]
_Firefox 85.0.1_

Since version 0.7.6, dark mode doesn't work.

It doesn't matter which style option I chose when I click on the addon button.

EDIT: When I go back to 0.7.4, it works again!

**Comment by m-khvoinitsky** [comment]
Well, that's strange.
Is this happening on all websites?
How does it looks like? Like completely without the add-on or some partial styling works?
Desktop Firefox? Which OS (probably doesn't matter, but still)? Are there any other add-ons?
Can you check for console errors?
* `about:debugging` -> This Firefox -> Extensions -> Dark Background and Light Text -> Inspect -> Console
* Menu -> Web Developer -> Toggle Tools -> Console

(this two are different consoles, show different errors and both are important)

**Comment by ArcticGems** [comment]
In order to answer your comment, I updated to 0.7.6 again and now it works!

Weird... a Firefox glitch maybe?? :confused:

**Comment by ArcticGems** [comment]
@m-khvoinitsky 
It works now, but I answer your questions anyway.

> 
> 
> Well, that's strange.
> Is this happening on all websites?

All

> How does it looks like? Like completely without the add-on or some partial styling works?

As if your addon wasn't installed

> Desktop Firefox? Which OS (probably doesn't matter, but still)? Are there any other add-ons?

 Desktop Firefox 85.0.2 on Windows 7 and my list of extensions =

```
Absolute Enable Right Click & Copy
Auto Tab Discard
Automatic Reader View
Bookmarks clean up
Calculator
Changelogger
Checkmarks
Clear Cache
ClearURLs
Cookie Quick Manager
CookieMaster
Copy All Tab Urls
Copy PlainText
Copy Text Link
Dark Background and Light Text
Disable WebRTC
Don't touch my tabs! (rel=noopener)
Download Manager (S3)
DownThemAll!
Duplicate Tabs Closer
Feedbro
Forget about this site
Fuck Popups	extension
Google search link fix
Image Picka
Link Alert
MergeMarks
minerBlock
Multiple Paste and Go Button
New Tab Override
NoScript
OneTab
Open Link with New Tab
Open Tabs Next to Current
Popup Bookmarks
Privacy Badger
Secure Password Generator
Select After Closing Current
Snap Links
Tab Counter
tabs2txt
uBlock Origin
X-notifier
```

> Can you check for console errors?
> 
>     * `about:debugging` -> This Firefox -> Extensions -> Dark Background and Light Text -> Inspect -> Console

I got this. actually there where hundreds of "Uncaught (in promise) Error" lines above this list =
```
Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist. undefined
Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist. undefined
Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist. undefined
Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist. undefined
Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist. undefined
Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist. undefined
Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist. undefined
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. 2 webrequest.js:107
TypeError: this.contentWindow is null ExtensionCommon.jsm:499:15
Promise rejected after context unloaded: Actor 'Conduits' destroyed before query 'RuntimeMessage' was resolved
fingerprinting.js:342
Promise rejected after context unloaded: Actor 'Conduits' destroyed before query 'RuntimeMessage' was resolved
dnt.js:64
Promise rejected after context unloaded: Actor 'Conduits' destroyed before query 'RuntimeMessage' was resolved
Messages.js:69
Promise rejected after context unloaded: Actor 'Conduits' destroyed before query 'RuntimeMessage' was resolved
content.js:1
InvalidStateError: An exception was thrown StoragePrefs.js:43
Uncaught (in promise) Error: window.do_it is not a function undefined
```

>     * Menu -> Web Developer -> Toggle Tools -> Console
> 

I get this on github.com =
```
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). utils.js:35:9
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). utils.js:35:9
Content Security Policy: The page’s settings blocked the loading of a resource at data: (“media-src”).
caught exception config.js:35:13
Error: An unexpected error occurred config.js:36:13
onmozfullscreenchange is deprecated. minerkill.js:22:7
onmozfullscreenerror is deprecated. minerkill.js:22:7
```

**Comment by Janaue** [comment]
slashdot.org doesn't work with the new version. I use the stylesheet processor option and i think the remaining ones are stock.

**Comment by m-khvoinitsky** [comment]
> In order to answer your comment, I updated to 0.7.6 again and now it works!
> 
> Weird... a Firefox glitch maybe?? confused

Yeah, looks like.

**Comment by m-khvoinitsky** [comment]
> slashdot.org doesn't work with the new version. I use the stylesheet processor option and i think the remaining ones are stock. I am on firefox esr and my profile hasn't otherwise changed between the update of the module. I have not tried on a clean profile though.

Can you also provide [the same debugging information](https://github.com/m-khvoinitsky/dark-background-light-text-extension/issues/287#issuecomment-776240561)? I've tried ESR and it works for me. Also, try to clear cache and check if it helps.

**Comment by Janaue** [comment]
> 
> 
> > slashdot.org doesn't work with the new version. I use the stylesheet processor option and i think the remaining ones are stock. I am on firefox esr and my profile hasn't otherwise changed between the update of the module. I have not tried on a clean profile though.
> 
> Can you also provide [the same debugging information](https://github.com/m-khvoinitsky/dark-background-light-text-extension/issues/287#issuecomment-776240561)? I've tried ESR and it works for me. Also, try to clear cache and check if it helps.

Well I upgraded again to the latest version and now it works on my profile. Perhaps it was due to old UBO list on firefox. I updated them just before upgrading.

At the time of my message, it was as if there was no CSS on the site. All the text was stuck on the left. The top of the page was all the menus [1 menu per line]. and then just naked text of the articles.
