### ISSUE TITLE
Disable globally but enable for individual site

### ISSUE THREAD

**Issue by fan-h** [m-khvoinitsky/dark-background-light-text-extension#290]
is there a way that you can disable the dark background globally but enable it for individual sites?

**Comment by m-khvoinitsky** [comment]
Yes.
Add-on Preferences → Default method of changing page colors → Disabled.
Now you can choose "Stylesheet Processor" or any other only for needed websites.

I have some plans to redesign the add-on to make this feature much more obvious among other things.
