### ISSUE TITLE
Hotkeys for global on/off switch

### ISSUE THREAD

**Issue by m-khvoinitsky** [m-khvoinitsky/dark-background-light-text-extension#3]

**Comment by m-khvoinitsky** [comment]
Until this feature will be implemented, there is a workaround:

1. Install [Dorando keyconfig](https://addons.mozilla.org/en-US/firefox/addon/dorando-keyconfig/) add-on
2. Go to Dorando keyconfig preferences (Menu → Add-ons → Extensions → Dorando keyconfig → Preferences)
3. "Add a new key" button
4. Pick whatever Name you want, for example "Dark Background & Light Text toggle"
5. Check "Global"
6. paste following code:
```
let prefs = Components.classes["@mozilla.org/preferences-service;1"].getService(Components.interfaces.nsIPrefBranch);
let key = 'extensions.jid1-QoFqdK4qzUfGWQ@jetpack.enabled';
prefs.setBoolPref(key, ! prefs.getBoolPref(key));
```
7. "OK"
8. assing some hotkey to newly created "key"
9. "Apply"
10. enjoy

**Comment by Natotela** [comment]
Is it merely copy-paste-assign? It's not executing toggle for me, what am I missing?

**Comment by m-khvoinitsky** [comment]
It won't work with 0.5.14+.

**Comment by m-khvoinitsky** [comment]
There is an issue with [commands](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/commands) is that you can't change hotkey at runtime.

**Comment by m-khvoinitsky** [comment]
Will work in the nearest update with Firefox 60+.
