### ISSUE TITLE
Blink/short delay until page load - FF 89.0.2

### ISSUE THREAD

**Issue by peter-kehl** [m-khvoinitsky/dark-background-light-text-extension#303]
Hi Mikhail,
Thank you for this eye saver.

Unfortunately, around Firefox update to 89.0.2 (on Linux x64) it started blinking/being temporary off on every page load. The add-on does work, but only about a second after the page gets loaded.

If you'd like me to investigate, please suggest how.

**Comment by m-khvoinitsky** [comment]
Hello.

> 89.0.2 (on Linux x64)

Same here, works well for me under both Wayland and X11.

> If you'd like me to investigate, please suggest how.

Is this happening every time on every page? Are there any errors in [Browser Console](https://developer.mozilla.org/en-US/docs/Tools/Browser_Console)?

**Comment by peter-kehl** [comment]
Seems to work with new Firefox. Thank you.
