### ISSUE TITLE
Firefox 102 seemed to affect this add-on

### ISSUE THREAD

**Issue by changmw** [m-khvoinitsky/dark-background-light-text-extension#331]
Firefox 102 seemed to break mode "Invert" of this add-on. It didn't happened to all website I visited, but one web-ui of a software called DVBViewer Pro Media Server. This add-on failed to turn white background into black.

The problem didn't appear when I was using older version of Firefox.

Thank you for your attention!

**Comment by believableUN** [comment]
It also happens to me. It even breaks the (empty) background of new tabs.

**Comment by gooly** [comment]
Since FF 104.0.2 (64-Bit) things getting worse.
E.g. here: https://www.mql5.com/en/articles/11394
the text that should become become light gray is almost black and unreadable using default set up :(
What works are "Simply css" and "invert" (but invert looks ugly)

**Comment by SeriousHoax** [comment]
Same issue here. The Default/Stylesheet processor is completely/semi breaking many sites. I'm having to use the Simple CSS option.
Example: 
https://www.microsoft.com/security/blog/2022/09/08/microsoft-investigates-iranian-attacks-against-the-albanian-government/

**Comment by SeriousHoax** [comment]
> 

Sorry, false positive. It was a bug related to the "Facebook Container" extension. It has been fixed with a new update of the extension.
https://github.com/mozilla/contain-facebook/issues/858#issuecomment-1240765493

**Comment by SeriousHoax** [comment]
> > 
> 
> Sorry, false positive. It was a bug related to the "Facebook Container" extension. It has been fixed with a new update of the extension. [mozilla/contain-facebook#858 (comment)](https://github.com/mozilla/contain-facebook/issues/858#issuecomment-1240765493)

No, some problems still remains.
Like there's an attached video here which is not visible in Stylesheet processor and Simple CSS mode.
![image](https://user-images.githubusercontent.com/29574622/189307520-2e42dd87-e4bb-4135-ada1-c7b564051f93.png)
Site: https://www.bleepingcomputer.com/news/security/gifshell-attack-creates-reverse-shell-using-microsoft-teams-gifs/

**Comment by m-khvoinitsky** [comment]
Does anyone still experience same issues? I've tried all mentioned pages and they all work with mentioned methods. Seems that it wasn't DBLT issue.

**Comment by SeriousHoax** [comment]
> Does anyone still experience same issues? I've tried all mentioned pages and they all work with mentioned methods. Seems that it wasn't DBLT issue.

Yeah, looks like it wasn't an issue related to the extension. Everything seems fine now.

**Comment by m-khvoinitsky** [comment]
Thanks.
