### ISSUE TITLE
Extension disabled after upgrading to Firefox 110.0.1

### ISSUE THREAD

**Issue by code-affinity** [m-khvoinitsky/dark-background-light-text-extension#347]
A few days ago, the extension completely stopped working.  The color inversion is not being applied to any web pages.  When I bring up the preferences menu by clicking on the extension's icon in the toolbar, all of the displayed options are disabled.

I upgraded to Firefox 111.0 and the problem persists.

**Comment by m-khvoinitsky** [comment]
What if you check/uncheck "Enabled" checkbox at the top? May be you accidentally pressed the hotkey which globally disables it?

**Comment by code-affinity** [comment]
Wow, I feel foolish. That was the problem, thank you.
