### ISSUE TITLE
v0.5.6: marked as Firefox 38+ compatible but actually works with 45+

### ISSUE THREAD

**Issue by xphnx** [m-khvoinitsky/dark-background-light-text-extension#35]
The addon stopped working in my Android after 06.09.2016 update. Uninstall and reinstall doesnt fix it. Unistall and downgrade to 0.5.5 doesnt fix it.
Cyanogenmod 13 hammerhead - Icecat 38.8.0 Android.
Thanks!
PD: Probably not very important because it an older version of the browser. For now I will use Firefox 48.0

**Comment by xphnx** [comment]
Yesterday the addon stops working in Firefox 48 too. 

In Icecat I do: uninstall, clean data and cache, reinstall 0.5.6=dont work
unistall, clean data and cache, reinstall 0.5.5=works
update to 0.5.6=dont work

**Comment by m-khvoinitsky** [comment]
Updated title to reflect the actual issue. Working on a fix.

**Comment by xphnx** [comment]
The addon gets autoupdated.
Now 0.5.6 works for me in both Firefox 48 and Icecat 38.

**Comment by m-khvoinitsky** [comment]
Are you sure about Icecat/Firefox 38 and 0.5.6? 0.5.6 definitely should not work in 38. While 0.5.7 should.

**Comment by xphnx** [comment]
Sure.
![screenshot_20160913-193727](https://cloud.githubusercontent.com/assets/4024412/18485017/4dcce58a-79eb-11e6-8f71-883e535c763e.png)
![screenshot_20160913-193758](https://cloud.githubusercontent.com/assets/4024412/18485016/4dcab71a-79eb-11e6-9aa2-57989e208fc2.png)
![screenshot_20160913-193906](https://cloud.githubusercontent.com/assets/4024412/18485018/4dd0bb2e-79eb-11e6-9de6-372bdce389a8.png)
![screenshot_20160913-193937](https://cloud.githubusercontent.com/assets/4024412/18485019/4dd1ef76-79eb-11e6-8a3c-a202022963aa.png)

**Comment by m-khvoinitsky** [comment]
That's strange, really. Because in 1bdd1455e47bc726225419cd93f77b3d060f5c2c I've fixed important issue for older Firefox. 0.5.7 is broken with fennec too. I've removed compatibility with fennec for this version to prevent auto-update.

BTW, what is your device? What DPI it has? Page action ("Aa" icon) icon looks too tiny.

**Comment by xphnx** [comment]
Yes. Nexus 5 , CM 13. 480 DPI (default)


In Firefox 48 it looks:
![screenshot_20160913-205135](https://cloud.githubusercontent.com/assets/4024412/18487087/2a1a5ca4-79f4-11e6-844b-1bfe6444d5ba.png)

**Comment by m-khvoinitsky** [comment]
Thank you. So, it seems to be older versions issue.

**Comment by m-khvoinitsky** [comment]
Fixed in 0.5.8.
