### ISSUE TITLE
Restartless update of the code inside process script

### ISSUE THREAD

**Issue by xphnx** [m-khvoinitsky/dark-background-light-text-extension#36]
After the last update 0.5.6, In stylesheet processor:

1.- Selecting doesnt color text.
2.- Some texts are still dark

![sin titulo](https://cloud.githubusercontent.com/assets/4024412/18311691/fadaf4dc-7505-11e6-94af-c1a25618e2f7.png)

Invert mode works fine. 
In Mozilla Firefox 47.0.1 and probablyin 48 too (not completetly sure).

Thanks for this great job!

**Comment by m-khvoinitsky** [comment]
It works for me:
![screen shot 2016-09-07 at 15 26 30](https://cloud.githubusercontent.com/assets/16675892/18311882/89cf3d52-750f-11e6-9330-c4b20809e06a.png)
Can you screenshot add-on's settings page?

**Comment by xphnx** [comment]
Sure
![sin titulo2](https://cloud.githubusercontent.com/assets/4024412/18312205/d9f13350-7508-11e6-88dd-063640d6c392.png)

Selection color doenst aply too...

**Comment by m-khvoinitsky** [comment]
I've checked 45 ESR - works fine too.
Which other add-on do you use? Operating system?
Have you tried it on a fresh profile?

**Comment by lepieru** [comment]
>  1.- Selecting doesnt color text.

I have the same problem with __Stylesheet processor__ and __Simple CSS__ but not with __Invert__.

It worked well in a previous version.

**Comment by xphnx** [comment]
I have that issues in another PC - MS Windows 7. Now I am in my laptop (GNU/Linux Manjaro) and it works properly (both select and  dark text).

Tomorrow I will do some tests on the Windows machine. Addons: Ublock Origin, Https everywhere, Privacy badger, YouTube Video and Audio Downloader, User-agent switcher. I remember changing the useragent (with the last addon) to Android it works fine. Tomorrow I will complete the info.

**Comment by m-khvoinitsky** [comment]
I've just tested it on Windows 7 VM and it works.
Can you attach an output from browser console (Menu -> Developer -> Browser Console)? For privacy reasons you can send it to me by email and\or cut any private information from it (if there is some). It would be appreciated.

**Comment by xphnx** [comment]
Today it works! ... so I think its solved. Sorry for the inconveniences.
Regards.

**Comment by m-khvoinitsky** [comment]
However, I've reproduced the issue.
The reason is this Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1051238
Due to it most part of the add-on worked properly except for a CSS template rendering. There is a bit new template format so we had (due to the bug) new templates but old template rendering code.
The workaround is restart the browser after add-on upgrade.
I'll add a workaround to the code.

**Comment by m-khvoinitsky** [comment]
This is a bit more complex issue. Part two: https://discourse.mozilla-community.org/t/using-add-on-sdk-modules-outside-of-add-on-sdk/10754
