### ISSUE TITLE
Feature Suggestion: Add ability to change the global toggle keybind

### ISSUE THREAD

**Issue by Test-Account666** [m-khvoinitsky/dark-background-light-text-extension#373]
I'm using the F2 key for something different already and it's kinda annoying to get blinded by light mode websites because of it

**Comment by siffegh** [comment]
You can assign a different key combo in Manage Extension Shortcuts.

![image](https://github.com/user-attachments/assets/38465c7c-7d24-4515-9d20-0aba2f73b200)

**Comment by Test-Account666** [comment]
Ooof, sorry about that
