### ISSUE TITLE
Automatically disable on sites that already have dark backgrounds

### ISSUE THREAD

**Issue by blackwind** [m-khvoinitsky/dark-background-light-text-extension#41]
Of the 30 site-specific rules in my configuration, 28 are "Disabled" rules for sites that were designed with a dark background and light text in the first place. To simplify configuration, I'd love to see an option to automatically ignore sites with a background darker than a configurable value.

**Comment by m-khvoinitsky** [comment]
Well, I'm afraid that it will not be very easy to do, detecting if website is dark is not the trivial task.
For example, I've just checked a dark web.skype.com interface and it has signs of it's darkness only in 6th (!) descendant of `<html>`.
If I come up with some solution, it will still have some amount of errors (as it could be only heuristic algorithm, not something strictly definite). Imagine, now you have 28 "Disabled" rules, after you will have may be much less such rules but you will have probably larger amount of "force enabled" rules which fixes false-positive dark theme detection.
Also, there are some sites which are mostly dark but not completely (like GMail dark theme - it's all dark except for emails).
