### ISSUE TITLE
Stylesheet processor: ugly shadow when global background is grey

### ISSUE THREAD

**Issue by Honigmelone** [m-khvoinitsky/dark-background-light-text-extension#43]
Hi,

I love this addon however, when the global background is something grey instead of the default black sometimes text has an ugly shadow. See this example:
![screenshot from 2016-10-29 15-14-22](https://cloud.githubusercontent.com/assets/11220071/19829758/730399c0-9dea-11e6-9b15-69e498dff129.png)

How to reproduce:
1.) set default background colour to #3D3D3D
2.) set stylesheet processor as default method
2.) go to google.de

Actual Result see above,

Expected Result (obtained with simple css option which has other drawbacks):
![screenshot from 2016-10-29 15-18-43](https://cloud.githubusercontent.com/assets/11220071/19829794/0480ad3e-9deb-11e6-8c4a-adcdb53026e9.png)

**Comment by m-khvoinitsky** [comment]
Yep. This "safety shadow" (needed in case when there is some arbitrary picture behind the text which colors can make text unreadable) should take it's color from background color setting.
It will be fixed in the next version.
