### ISSUE TITLE
Unloaded tabs refreshed in the background are not made dark

### ISSUE THREAD

**Issue by AndrewFerr** [m-khvoinitsky/dark-background-light-text-extension#45]
Steps to reproduce:
0. Enable DB&LT and make sure that tabs are set to not load in the background (about:config ->browser.tabs.loadDivertedInBackground = false)
1. Open a few tabs on sites where DB&LT is not disabled.
2. Close the window.
3. Restore that window somehow (like History->Restore Closed Windows).
4. Right click on the tab bar and click "Reload All Tabs".
5. View one of the tabs that the window didn't open with.

Every tab other than the one that the window opened with will not be made dark (or with only some parts of the page made dark).

Refreshing each tab individually will restore darkening.

**Comment by AndrewFerr** [comment]
The same issue also happens for unloaded tabs refreshed by the [Tab Scope](https://addons.mozilla.org/en-US/firefox/addon/tab-scope/) add-on ("When previewing an unloaded tab, load it immediately"). So it looks like this issue is related to loading tabs in a background context in general.

Note that refreshing a non-darkened page will apply darkening to it, even if the page is reloaded via "Reload All Tabs" or the refresh button in a Tab Scope preview window.

**Comment by m-khvoinitsky** [comment]
This is a drawback of fixing #15.
As a workaround, you can enable [e10s](https://wiki.mozilla.org/Electrolysis).

**Comment by AndrewFerr** [comment]
I just tried enabling e10s and the problem does indeed get fixed. Since e10s is eventually going to be on by default, maybe it's fine to ignore this issue.

**Comment by m-khvoinitsky** [comment]
It is still an issue when a page is loaded in main process rather than content process. Such pages are firefox internal pages like `about:addons`, `about:preferences` and add-on's pages.

**Comment by m-khvoinitsky** [comment]
This won't be the case for WebExtensions so closing it.
