### ISSUE TITLE
"Invert" mode for image pages moves image upward

### ISSUE THREAD

**Issue by AndrewFerr** [m-khvoinitsky/dark-background-light-text-extension#50]
When viewing an image in its own page (via "View Image", "View Background Image", or simply visiting the URL of an image file), "Invert" mode will display the image shifted high up in the page, sometimes even higher than the top of the page, cutting it off or hiding it entirely.

Try viewing the Google logo with google.com set to "Invert":
https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png

For me, it appears like this:
![dbltcutoffimage](https://cloud.githubusercontent.com/assets/3271094/20230913/62689ec0-a82c-11e6-877b-2c11eef1c920.png)

Maybe this is what #18 was talking about, as this issue sometimes hides the entire picture, leaving only a black background behind.

**Comment by Tyf0x** [comment]
Most probably a firefox bug.
See:
- http://stackoverflow.com/a/37951075/1268192
- https://bugzilla.mozilla.org/show_bug.cgi?id=1106895
- https://bugzilla.mozilla.org/show_bug.cgi?id=1258421

**Comment by m-khvoinitsky** [comment]
@Tyf0x, exactly.
For some reason, after applying filter to an element, all its positioned descendants behave like if it was positioned.
I've tried to workaround it but:
* in the common case: it's hard (or impossible) not to get other drawbacks, usually more severe
* in case of "image-only pages": It's hard to distinguish such pages from all the rest (at least using CSS).
