### ISSUE TITLE
Find a better way to overwrite "default" colors

### ISSUE THREAD

**Issue by m-khvoinitsky** [m-khvoinitsky/dark-background-light-text-extension#51]
"default" here means the color wich elements gets if it and all its ancestors have `transparent` or `inherit`.
Previous tries:
#25 889369d88b9d9f9bfc64946b22e3681b3dfb3c9d 0de708068a4555bf2b99adcdc60a806b3f0272ec (background color)
#29 a529c3e59deb07a580c90fd4a507aaaff1160a52 (text color)

Current issues:
* Google plus:
![screen shot 2016-11-13 at 23 11 09](https://cloud.githubusercontent.com/assets/16675892/20248516/d0310c28-a9f6-11e6-817b-0c899182a9f5.png)
Google plus notification popup is an iframe and it assumes that it's background color is transparent.
Possible solution: set background color of top-level element (usually `<html>`) **only** for top-level windows (i. e. not iframes)

* #48
* [OneNote Web Clipper](https://addons.mozilla.org/en-US/firefox/addon/onenote-clipper/) -> Region
* Firefox screenshots → region highlight overlay.
* #92

**Comment by larry77** [comment]
It is an excellent extension and far better than any style I have tried with stylish. I have troubles only on a few sites where the background color is too "aggressive" i.e. it replaces e.g. the background color of an applet. See e.g. what happens to the chessboard here

http://www.chessgames.com/perl/chessgame?gid=1143163

Keep up the good work and thanks.

**Comment by m-khvoinitsky** [comment]
@larry77, the reasons of such behavior can be different.
In case of this chessboard, they use obsolete html attribute `bgcolor` which [I do not support properly](https://github.com/m-khvoinitsky/dark-background-light-text-extension/blob/2b8e16de69bdaf4b767aeb26e478179db36d50e8/data/methods/stylesheet-processor.css#L14) (because it's obsolete and rarely used). They even don't use it (final colors a set by CSS).

You can paste this code to [command line](https://developer.mozilla.org/en-US/docs/Tools/Web_Console/The_command_line_interpreter) of [Firefox Developer Tools Web Console](https://developer.mozilla.org/en-US/docs/Tools/Web_Console/Opening_the_Web_Console) to see how it will look like without it:
```Array.prototype.forEach.call(document.querySelectorAll('[bgcolor]'), element => element.removeAttribute('bgcolor'));```
![screen shot 2016-11-19 at 17 38 06](https://cloud.githubusercontent.com/assets/16675892/20456184/bb27ca18-ae80-11e6-8e53-9963ed6e6291.png)


You can try to ask website developers to remove this obsolete (and unused) attribute.

**Comment by m-khvoinitsky** [comment]
I suppose setting background-color only for top-level windows (not iframes) is the best I can do here. So, closing for now.

**Comment by m-khvoinitsky** [comment]
is_top_level_frame doen't seems work.
