### ISSUE TITLE
Style not applied to some XUL documents in Firefox 51+

### ISSUE THREAD

**Issue by blackwind** [m-khvoinitsky/dark-background-light-text-extension#52]
In Firefox 51 and above, certain XUL documents like about:addons and about:preferences aren't styled. about:addons can be worked around using the Simple CSS option (though it produces an extremely ugly result), while about:preferences stubbornly remains bright white no matter which option you choose.

**Comment by m-khvoinitsky** [comment]
I've just tried current devedition and nightly: about:addons works as expected while about:preferences for some reason completely ignores it's per-site settings (So, may be you use "Disabled" as default and try to enable it only for certain websites?).

**Comment by blackwind** [comment]
Tracked down to the "Alternative appearance" setting for each document in Classic Theme Restorer, which are both apparently set by default for some reason. Sorry for the false alarm.
