### ISSUE TITLE
Library window not dark

### ISSUE THREAD

**Issue by redlap2** [m-khvoinitsky/dark-background-light-text-extension#73]
Firefox 52.0.2 on linux.

When I open the Library window to see my downloads, it has white background.

**Comment by m-khvoinitsky** [comment]
Can you attach a screenshot?

**Comment by redlap2** [comment]
Here you can see the 2 windows at the same time:

![w8qfnsr](https://cloud.githubusercontent.com/assets/25507269/24680575/c0083f1e-1991-11e7-923a-4320a07717bc.png)

**Comment by m-khvoinitsky** [comment]
This is intentional - Library window uses your desktop theme (in case of linux - GTK 3 theme). You can try to use some dark GTK 3 theme (like adwaita-dark or breeze-dark).
