### ISSUE TITLE
Broken on recent nightly

### ISSUE THREAD

**Issue by robsmith11** [m-khvoinitsky/dark-background-light-text-extension#76]
The add-on stopped working a few weeks ago with firefox nightly.  Enabling and disabling it has no effect on any page's colors.  It was working fine with a nightly from March.  I'm using arch linux 64-bit.

**Comment by robsmith11** [comment]
Oops.. just saw #74.  Sorry for the noise.

**Comment by m-khvoinitsky** [comment]
Fixed in [latest update](https://addons.mozilla.org/en-US/firefox/addon/dark-background-light-text/versions/?page=1#version-0.5.10)
