### ISSUE TITLE
Not working on windows 10 firefox 53(32 bit)

### ISSUE THREAD

**Issue by dEvasEnApati** [m-khvoinitsky/dark-background-light-text-extension#78]
The colors don't switch after installations. Choosing 'Options' in the 'Addons' page opens a tab which says 'Error. You should not see this'.

**Comment by m-khvoinitsky** [comment]
I've just checked it on Windows 10 and it works. Try to open Menu → Developer → Browser Console and paste here any errors that appears there.

**Comment by dEvasEnApati** [comment]
I reinstalled firefox itself and the problem seems to correct itself. Thanks for the check!
