### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by Jookia** [m-khvoinitsky/dark-background-light-text-extension#80]
Hey there! On the mozilla addon page it says 'MPL' license, in package.json it says 'MIT' and there's no 'LICENSE' file.

**Comment by robinpaulson** [comment]
Yep, I'd like to know this too.

**Comment by sebastianschauenburg** [comment]
Could a "COPYING" file be added by the author please? That should quickly solve this.

**Comment by m-khvoinitsky** [comment]
Added Mozilla Public License Version 2.0 LICENSE file to all branches.
