### ISSUE TITLE
Incompatible with Firefox 49.0.2

### ISSUE THREAD

**Issue by Pr0xyBug** [m-khvoinitsky/dark-background-light-text-extension#83]
Title.

**Comment by m-khvoinitsky** [comment]
Why it should be? This version is outdated, not supported by Mozilla and it isn't even ESR. What is the point?

**Comment by m-khvoinitsky** [comment]
To clarify: I always support at least latest ESR which is 52 for now. This is also clearly noted in [version compatibility](https://addons.mozilla.org/en-US/firefox/addon/dark-background-light-text/versions/?page=1#version-0.5.10). So, there are no bug here.
