### ISSUE TITLE
Make last jetpack version compatible with SeaMonkey

### ISSUE THREAD

**Issue by m-khvoinitsky** [m-khvoinitsky/dark-background-light-text-extension#85]
Currently, the only broken thing in SeaMonkey's jetpack I've found is tabs.activeTab which should be worked around.

**Comment by dumol** [comment]
Any news on this? I've downloaded manually with Firefox from Mozilla's site, edited install.rds, and added the extension manually in SeaMonkey, but it doesn't fully work. I can change options, enable/disable the extension, but no change in colours for the web pages. Works flawlessly in Firefox ESR though.

Also, I'm using this daily on Firefox for Android and it is the only thing that makes me endure its slowness. My eyes are grateful every evening, thank you!

**Comment by m-khvoinitsky** [comment]
Seems to be done. Please, try to build (using jpm) a version from 0179719981ddf1375f03adec7120b0ca537d596d (jetpack branch) (don't forget about `git submodule init; git submodule update`)

**Comment by dumol** [comment]
Had to learn how to build an XPI, but Mozilla docs were straightforward. In the end, I confirm **it works**, including for the mail client! Very nice… :-]

**Comment by m-khvoinitsky** [comment]
[Released on AMO](https://addons.mozilla.org/en-US/firefox/addon/dark-background-light-text/versions/?page=1#version-0.5.13).
Unfortunately, I can't guarantee that following updates will be compatible. In particular, embedded WebExtensions seems to be broken on 2.49.1. So, I suppose it will be first and last compatible version (which is not a big deal — anyway, next, webextension version, will not be compatible for sure). Now I'm trying to figure out how to ensure that users will be able to download *last compatible* version from AMO even if it's not the most recent version.

**Comment by dumol** [comment]
Thank you! I'm on 2.48, the version packaged with OpenBSD 6.2.

Don't know about keeping this available in AMO, perhaps releasing it separately, under a slightly different name? I wouldn't mind for sure.

**Comment by m-khvoinitsky** [comment]
Yep, I did it that way.
Now it's here: https://addons.mozilla.org/seamonkey/addon/dark-bg-light-text-seamonkey

**Comment by dumol** [comment]
Two suggestions: verified author would be nice and donation link is a must. :-]

**Comment by m-khvoinitsky** [comment]
> verified author would be nice

I'm not sure that it's possible now — addons.mozilla.org implemented their own signing.

> donation link is a must. :-]

I'm working on it.
