### ISSUE TITLE
Enhancement: text selection with reverse colors

### ISSUE THREAD

**Issue by mixmastamyk** [m-khvoinitsky/dark-background-light-text-extension#87]
Hi, awesome work.

I have a small problem, where the default colors I've set by the this extension clash with the text-selection colors set by your tool (or inherited from the OS).  Previously I've handled this by setting the text-selection colors to the opposite (reverse bg and fg) of what the page is set to, but the extension I used for that no longer works.  

In short, I'd like the "default" setting of your tool to set the text-selection colors to the inverse of the colors chosen for the page.  Thanks for your consideration.

P.S. Text selection colors can be styled like so:

- https://css-tricks.com/overriding-the-default-text-selection-color-with-css/

**Comment by mixmastamyk** [comment]
Just looked again, and realized the problem is that when selecting the text it doesn't change its foreground color.

**Comment by m-khvoinitsky** [comment]
Yep, It makes sense to have an ability to configure foreground and background colours separately of selected text.

**Comment by m-khvoinitsky** [comment]
Duplicates #63
