### ISSUE TITLE
Refactor URL handling code

### ISSUE THREAD

**Issue by m-khvoinitsky** [m-khvoinitsky/dark-background-light-text-extension#9]
Currently IPv6:port and IPv6 is broken completely while other seems to work but may be buggy.

**Comment by m-khvoinitsky** [comment]
Probably, url handling code should be migrated to [URL()](https://developer.mozilla.org/en-US/docs/Web/API/URL)

**Comment by Exagone313** [comment]
Hi,

Do you plan to fix this bug? If I have the time I could look into it, but for example I have also a bug in Firefox I need to fix, etc... Those bugs almost nobody care you know.

**Comment by m-khvoinitsky** [comment]
Hello.
Sure, I do. Actually, once I've already tried to fix it but it turned out to be not so easy. The problem is that related code ([here](https://github.com/m-khvoinitsky/dark-background-light-text-extension/blob/89a0ad4c5bc6f27012ca1a6b432f86c107ed2c09/lib/index.js#L209) and [here](https://github.com/m-khvoinitsky/dark-background-light-text-extension/blob/89a0ad4c5bc6f27012ca1a6b432f86c107ed2c09/lib/index.js#L138)) is complicated mix of special cases where it's hard to change something without breaking something else. I guess it's better to rewrite it almost completely, probably changing "saved url" format to something more structured than plain string. Anyway, I will have to rewrite it while porting to WebExtensions.

**Comment by m-khvoinitsky** [comment]
Things to consider: https://palant.de/2018/08/29/password-managers-please-make-sure-autofill-is-secure
