### ISSUE TITLE
Doesn't work on Youtube any more

### ISSUE THREAD

**Issue by idlekaty** [m-khvoinitsky/dark-background-light-text-extension#90]
I think Youtube must have had some major update. Not only does "Dark Background" no longer replace youtube's background to my preferred colour (why is white so painful?!), but also I saw an advert on a video, which shocked me as I have been happily U-blocking for ages (I know that is nothing to do with this app - just some further evidence that "something's up").
Will this add-on get updated work with the new Youtube?
Any ideas appreciated!

**Comment by m-khvoinitsky** [comment]
Make sure that you're using latest add-on version (0.5.11).

**Comment by idlekaty** [comment]
I am an idiot. Updated now! Thank you!

**Comment by m-khvoinitsky** [comment]
It happens.
