### ISSUE TITLE
legacy addon support

### ISSUE THREAD

**Issue by kr1shna-opensource** [m-khvoinitsky/dark-background-light-text-extension#97]
are you planning to support only webextensions ?

**Comment by CaptaPraelium** [comment]
This addon just stopped working for me with the latest ff update. If there's anything I can do to help, please let me know. My eyes hurt! :(

**Comment by m-khvoinitsky** [comment]
> This addon just stopped working for me with the latest ff update. If there's anything I can do to help, please let me know. My eyes hurt! :(

Which version? It should work with stable but not with beta. Compatible version is in development.

**Comment by Exagone313** [comment]
Even when enabling legacy extensions (at compile time + extensions.legacy.enabled config), it does not work in 57+, the icon is missing and the preference page is blank.

**Comment by kr1shna-opensource** [comment]
from the tweets and reddit posts, i jumped to conclusion that webextensions cant be used.
can i assume jetpack version will work on waterfox or is it specific to seamonkey ?
i am on android 5.1, waterfox 55.2

**Comment by kr1shna-opensource** [comment]
version 0.5.11 on waterfox 55.2 android 5.1 does not work.
when i tap icon, "Error. You should not see this"

**Comment by m-khvoinitsky** [comment]
No idea about Waterfox. According to their website, they're not going to disable WebExtensions or somehow else prevent them from running.

> can i assume jetpack version will work on waterfox or is it specific to seamonkey ?

For now, it works only in Firefox. It seems that Waterfox shold be compatible with Firefox add-ons but as it turns out it doesn't.
